// flow-typed signature: b76b7d6393b28494033a9df2686fcde9
// flow-typed version: <<STUB>>/@rest-hooks/endpoint_v^2.1.0/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rest-hooks/endpoint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rest-hooks/endpoint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rest-hooks/endpoint/dist' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/dist/index.umd.min' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/legacy/endpoint' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/legacy' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/legacy/indexEndpoint' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/legacy/interface' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/legacy/normal' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/legacy/types' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/legacy/utility' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/lib/endpoint' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/lib' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/lib/indexEndpoint' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/lib/interface' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/lib/normal' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/lib/types' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/lib/utility' {
  declare module.exports: any;
}

declare module '@rest-hooks/endpoint/src/endpoint' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rest-hooks/endpoint/dist/index' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/dist'>;
}
declare module '@rest-hooks/endpoint/dist/index.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/dist'>;
}
declare module '@rest-hooks/endpoint/dist/index.umd.min.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/dist/index.umd.min'>;
}
declare module '@rest-hooks/endpoint/legacy/endpoint.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/legacy/endpoint'>;
}
declare module '@rest-hooks/endpoint/legacy/index' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/legacy'>;
}
declare module '@rest-hooks/endpoint/legacy/index.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/legacy'>;
}
declare module '@rest-hooks/endpoint/legacy/indexEndpoint.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/legacy/indexEndpoint'>;
}
declare module '@rest-hooks/endpoint/legacy/interface.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/legacy/interface'>;
}
declare module '@rest-hooks/endpoint/legacy/normal.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/legacy/normal'>;
}
declare module '@rest-hooks/endpoint/legacy/types.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/legacy/types'>;
}
declare module '@rest-hooks/endpoint/legacy/utility.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/legacy/utility'>;
}
declare module '@rest-hooks/endpoint/lib/endpoint.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/lib/endpoint'>;
}
declare module '@rest-hooks/endpoint/lib/index' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/lib'>;
}
declare module '@rest-hooks/endpoint/lib/index.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/lib'>;
}
declare module '@rest-hooks/endpoint/lib/indexEndpoint.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/lib/indexEndpoint'>;
}
declare module '@rest-hooks/endpoint/lib/interface.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/lib/interface'>;
}
declare module '@rest-hooks/endpoint/lib/normal.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/lib/normal'>;
}
declare module '@rest-hooks/endpoint/lib/types.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/lib/types'>;
}
declare module '@rest-hooks/endpoint/lib/utility.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/lib/utility'>;
}
declare module '@rest-hooks/endpoint/src/endpoint.js' {
  declare module.exports: $Exports<'@rest-hooks/endpoint/src/endpoint'>;
}
