// flow-typed signature: a612f4a09d5b80f83aa83271240c0f9d
// flow-typed version: <<STUB>>/@rest-hooks/rest_v^3.0.1/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rest-hooks/rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rest-hooks/rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rest-hooks/rest/dist' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/dist/index.umd.min' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/legacy/EntityRecord' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/legacy/errors' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/legacy' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/legacy/legacy' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/legacy/paramsToString' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/legacy/paramsToString.native' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/legacy/Resource' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/legacy/SimpleResource' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/legacy/types' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/lib/EntityRecord' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/lib/errors' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/lib' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/lib/legacy' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/lib/paramsToString' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/lib/paramsToString.native' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/lib/Resource' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/lib/SimpleResource' {
  declare module.exports: any;
}

declare module '@rest-hooks/rest/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rest-hooks/rest/dist/index' {
  declare module.exports: $Exports<'@rest-hooks/rest/dist'>;
}
declare module '@rest-hooks/rest/dist/index.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/dist'>;
}
declare module '@rest-hooks/rest/dist/index.umd.min.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/dist/index.umd.min'>;
}
declare module '@rest-hooks/rest/legacy/EntityRecord.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy/EntityRecord'>;
}
declare module '@rest-hooks/rest/legacy/errors.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy/errors'>;
}
declare module '@rest-hooks/rest/legacy/index' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy'>;
}
declare module '@rest-hooks/rest/legacy/index.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy'>;
}
declare module '@rest-hooks/rest/legacy/legacy.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy/legacy'>;
}
declare module '@rest-hooks/rest/legacy/paramsToString.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy/paramsToString'>;
}
declare module '@rest-hooks/rest/legacy/paramsToString.native.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy/paramsToString.native'>;
}
declare module '@rest-hooks/rest/legacy/Resource.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy/Resource'>;
}
declare module '@rest-hooks/rest/legacy/SimpleResource.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy/SimpleResource'>;
}
declare module '@rest-hooks/rest/legacy/types.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/legacy/types'>;
}
declare module '@rest-hooks/rest/lib/EntityRecord.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib/EntityRecord'>;
}
declare module '@rest-hooks/rest/lib/errors.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib/errors'>;
}
declare module '@rest-hooks/rest/lib/index' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib'>;
}
declare module '@rest-hooks/rest/lib/index.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib'>;
}
declare module '@rest-hooks/rest/lib/legacy.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib/legacy'>;
}
declare module '@rest-hooks/rest/lib/paramsToString.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib/paramsToString'>;
}
declare module '@rest-hooks/rest/lib/paramsToString.native.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib/paramsToString.native'>;
}
declare module '@rest-hooks/rest/lib/Resource.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib/Resource'>;
}
declare module '@rest-hooks/rest/lib/SimpleResource.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib/SimpleResource'>;
}
declare module '@rest-hooks/rest/lib/types.js' {
  declare module.exports: $Exports<'@rest-hooks/rest/lib/types'>;
}
