// flow-typed signature: 4093f3d159a42a45cf08e7db02f2d16c
// flow-typed version: <<STUB>>/@fortawesome/fontawesome-svg-core_v^1.2.36/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/fontawesome-svg-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/fontawesome-svg-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/fontawesome-svg-core/attribution' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-svg-core/index.es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/fontawesome-svg-core/attribution.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-svg-core/attribution'>;
}
declare module '@fortawesome/fontawesome-svg-core/index.es.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-svg-core/index.es'>;
}
declare module '@fortawesome/fontawesome-svg-core/index' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-svg-core'>;
}
declare module '@fortawesome/fontawesome-svg-core/index.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-svg-core'>;
}
