version: "3.6"
networks:
  traefik-network:
    external: true

services:
  py-ispyb-ui:
    build:
      args:
        - NODE_ENV=development
      context: .
    environment:
      - NODE_ENV=development
    container_name: py-ispyb-ui
    labels:
      - "traefik.backend=py-ispyb-ui-localhost"
      - "traefik.frontend.rule=Host:py-ispyb-ui.localhost"
      - "traefik.docker.network=traefik-network"
      - "traefik.port=3000"
    volumes:
      - ./src:/usr/app/src
      - ./public:/usr/app/public
    networks:
      - traefik-network
    ports:
      - 5000:5000
 
