// flow-typed signature: 1456ba8f9515179b2d47b3d72edf780a
// flow-typed version: <<STUB>>/axios-hooks_v^3.0.0/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axios-hooks/cjs' {
  declare module.exports: any;
}

declare module 'axios-hooks/es' {
  declare module.exports: any;
}

declare module 'axios-hooks/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axios-hooks/cjs/index' {
  declare module.exports: $Exports<'axios-hooks/cjs'>;
}
declare module 'axios-hooks/cjs/index.js' {
  declare module.exports: $Exports<'axios-hooks/cjs'>;
}
declare module 'axios-hooks/es/index' {
  declare module.exports: $Exports<'axios-hooks/es'>;
}
declare module 'axios-hooks/es/index.js' {
  declare module.exports: $Exports<'axios-hooks/es'>;
}
declare module 'axios-hooks/src/index' {
  declare module.exports: $Exports<'axios-hooks/src'>;
}
declare module 'axios-hooks/src/index.js' {
  declare module.exports: $Exports<'axios-hooks/src'>;
}
