// flow-typed signature: 6e6bc6fe9b70be6b140444f34a4ec67e
// flow-typed version: <<STUB>>/bootswatch_v^5.1.3/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootswatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootswatch' {
  declare module.exports: any;
}
