// flow-typed signature: c84ac9cff671a0174dabbc47047c4697
// flow-typed version: <<STUB>>/qs_v^6.10.2/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qs/dist/qs' {
  declare module.exports: any;
}

declare module 'qs/lib/formats' {
  declare module.exports: any;
}

declare module 'qs/lib' {
  declare module.exports: any;
}

declare module 'qs/lib/parse' {
  declare module.exports: any;
}

declare module 'qs/lib/stringify' {
  declare module.exports: any;
}

declare module 'qs/lib/utils' {
  declare module.exports: any;
}

declare module 'qs/test/parse' {
  declare module.exports: any;
}

declare module 'qs/test/stringify' {
  declare module.exports: any;
}

declare module 'qs/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qs/dist/qs.js' {
  declare module.exports: $Exports<'qs/dist/qs'>;
}
declare module 'qs/lib/formats.js' {
  declare module.exports: $Exports<'qs/lib/formats'>;
}
declare module 'qs/lib/index' {
  declare module.exports: $Exports<'qs/lib'>;
}
declare module 'qs/lib/index.js' {
  declare module.exports: $Exports<'qs/lib'>;
}
declare module 'qs/lib/parse.js' {
  declare module.exports: $Exports<'qs/lib/parse'>;
}
declare module 'qs/lib/stringify.js' {
  declare module.exports: $Exports<'qs/lib/stringify'>;
}
declare module 'qs/lib/utils.js' {
  declare module.exports: $Exports<'qs/lib/utils'>;
}
declare module 'qs/test/parse.js' {
  declare module.exports: $Exports<'qs/test/parse'>;
}
declare module 'qs/test/stringify.js' {
  declare module.exports: $Exports<'qs/test/stringify'>;
}
declare module 'qs/test/utils.js' {
  declare module.exports: $Exports<'qs/test/utils'>;
}
