// flow-typed signature: 4da29a1c5147ab11cd49d86ec84b54e6
// flow-typed version: <<STUB>>/react-bootstrap-table2-toolkit_v^2.1.3/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap-table2-toolkit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap-table2-toolkit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit.min' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/context' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/provider' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/column-toggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/column-toggle/toggle-list' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/csv/button' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/csv/exporter' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/csv' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/op/csv' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/op' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/search/clear-button' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/search/context' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/search' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/src/search/SearchBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-toolkit/lib/statelessOp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit'>;
}
declare module 'react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit.min.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit.min'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/context.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/context'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/index' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/provider.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/provider'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/column-toggle/index' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/column-toggle'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/column-toggle/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/column-toggle'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/column-toggle/toggle-list.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/column-toggle/toggle-list'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/csv/button.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/csv/button'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/csv/exporter.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/csv/exporter'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/csv/index' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/csv'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/csv/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/csv'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/op/csv.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/op/csv'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/op/index' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/op'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/op/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/op'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/search/clear-button.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/search/clear-button'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/search/context.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/search/context'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/search/index' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/search'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/search/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/search'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/src/search/SearchBar.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/src/search/SearchBar'>;
}
declare module 'react-bootstrap-table2-toolkit/lib/statelessOp.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-toolkit/lib/statelessOp'>;
}
