// flow-typed signature: 9912196e5f473fe80dac22dc13f81f14
// flow-typed version: <<STUB>>/react-bootstrap-table2-paginator_v^2.1.2/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap-table2-paginator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap-table2-paginator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.min' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/const' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/data-context' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/page-button' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/page-resolver' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/page' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/pagination-handler' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/pagination-list-adapter' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/pagination-list-standalone' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/pagination-list' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/pagination-total-adapter' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/pagination-total-standalone' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/pagination-total' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/size-per-page-dropdown-adapter' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/size-per-page-dropdown-standalone' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/size-per-page-dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/size-per-page-option' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/standalone-adapter' {
  declare module.exports: any;
}

declare module 'react-bootstrap-table2-paginator/lib/src/state-context' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator'>;
}
declare module 'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.min.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/dist/react-bootstrap-table2-paginator.min'>;
}
declare module 'react-bootstrap-table2-paginator/lib/index' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib'>;
}
declare module 'react-bootstrap-table2-paginator/lib/index.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/const.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/const'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/data-context.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/data-context'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/page-button.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/page-button'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/page-resolver.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/page-resolver'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/page.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/page'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/pagination-handler.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/pagination-handler'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/pagination-list-adapter.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/pagination-list-adapter'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/pagination-list-standalone.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/pagination-list-standalone'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/pagination-list.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/pagination-list'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/pagination-total-adapter.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/pagination-total-adapter'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/pagination-total-standalone.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/pagination-total-standalone'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/pagination-total.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/pagination-total'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/pagination.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/pagination'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/size-per-page-dropdown-adapter.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/size-per-page-dropdown-adapter'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/size-per-page-dropdown-standalone.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/size-per-page-dropdown-standalone'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/size-per-page-dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/size-per-page-dropdown'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/size-per-page-option.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/size-per-page-option'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/standalone-adapter.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/standalone-adapter'>;
}
declare module 'react-bootstrap-table2-paginator/lib/src/state-context.js' {
  declare module.exports: $Exports<'react-bootstrap-table2-paginator/lib/src/state-context'>;
}
