// flow-typed signature: 94ba1aed9dae3e8db5da1dee640602e7
// flow-typed version: <<STUB>>/redux-promise-middleware_v^6.1.2/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-promise-middleware/dist/es' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/es/isPromise' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/isPromise' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/umd/redux-promise-middleware' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/dist/umd/redux-promise-middleware.min' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/src' {
  declare module.exports: any;
}

declare module 'redux-promise-middleware/src/isPromise' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-promise-middleware/dist/es/index' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/es'>;
}
declare module 'redux-promise-middleware/dist/es/index.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/es'>;
}
declare module 'redux-promise-middleware/dist/es/isPromise.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/es/isPromise'>;
}
declare module 'redux-promise-middleware/dist/index' {
  declare module.exports: $Exports<'redux-promise-middleware/dist'>;
}
declare module 'redux-promise-middleware/dist/index.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist'>;
}
declare module 'redux-promise-middleware/dist/isPromise.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/isPromise'>;
}
declare module 'redux-promise-middleware/dist/umd/redux-promise-middleware.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/umd/redux-promise-middleware'>;
}
declare module 'redux-promise-middleware/dist/umd/redux-promise-middleware.min.js' {
  declare module.exports: $Exports<'redux-promise-middleware/dist/umd/redux-promise-middleware.min'>;
}
declare module 'redux-promise-middleware/src/index' {
  declare module.exports: $Exports<'redux-promise-middleware/src'>;
}
declare module 'redux-promise-middleware/src/index.js' {
  declare module.exports: $Exports<'redux-promise-middleware/src'>;
}
declare module 'redux-promise-middleware/src/isPromise.js' {
  declare module.exports: $Exports<'redux-promise-middleware/src/isPromise'>;
}
