// flow-typed signature: 0133f16051e4a6541bc95ad5be43500f
// flow-typed version: <<STUB>>/web-vitals_v^2.1.2/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-vitals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web-vitals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web-vitals/base' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/getCLS' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/getFCP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/getFID' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/getLCP' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/getTTFB' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/bindReporter' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/generateUniqueID' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/getVisibilityWatcher' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/initMetric' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/observe' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/onBFCacheRestore' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/onHidden' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/polyfills/firstInputPolyfill' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/lib/polyfills/getFirstHiddenTimePolyfill' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/polyfill' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/modules/types' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/polyfill' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.base.iife' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.base' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.base.umd' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.iife' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals' {
  declare module.exports: any;
}

declare module 'web-vitals/dist/web-vitals.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web-vitals/base.js' {
  declare module.exports: $Exports<'web-vitals/base'>;
}
declare module 'web-vitals/dist/modules/getCLS.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/getCLS'>;
}
declare module 'web-vitals/dist/modules/getFCP.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/getFCP'>;
}
declare module 'web-vitals/dist/modules/getFID.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/getFID'>;
}
declare module 'web-vitals/dist/modules/getLCP.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/getLCP'>;
}
declare module 'web-vitals/dist/modules/getTTFB.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/getTTFB'>;
}
declare module 'web-vitals/dist/modules/index' {
  declare module.exports: $Exports<'web-vitals/dist/modules'>;
}
declare module 'web-vitals/dist/modules/index.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules'>;
}
declare module 'web-vitals/dist/modules/lib/bindReporter.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/bindReporter'>;
}
declare module 'web-vitals/dist/modules/lib/generateUniqueID.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/generateUniqueID'>;
}
declare module 'web-vitals/dist/modules/lib/getVisibilityWatcher.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/getVisibilityWatcher'>;
}
declare module 'web-vitals/dist/modules/lib/initMetric.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/initMetric'>;
}
declare module 'web-vitals/dist/modules/lib/observe.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/observe'>;
}
declare module 'web-vitals/dist/modules/lib/onBFCacheRestore.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/onBFCacheRestore'>;
}
declare module 'web-vitals/dist/modules/lib/onHidden.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/onHidden'>;
}
declare module 'web-vitals/dist/modules/lib/polyfills/firstInputPolyfill.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/polyfills/firstInputPolyfill'>;
}
declare module 'web-vitals/dist/modules/lib/polyfills/getFirstHiddenTimePolyfill.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/lib/polyfills/getFirstHiddenTimePolyfill'>;
}
declare module 'web-vitals/dist/modules/polyfill.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/polyfill'>;
}
declare module 'web-vitals/dist/modules/types.js' {
  declare module.exports: $Exports<'web-vitals/dist/modules/types'>;
}
declare module 'web-vitals/dist/polyfill.js' {
  declare module.exports: $Exports<'web-vitals/dist/polyfill'>;
}
declare module 'web-vitals/dist/web-vitals.base.iife.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.base.iife'>;
}
declare module 'web-vitals/dist/web-vitals.base.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.base'>;
}
declare module 'web-vitals/dist/web-vitals.base.umd.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.base.umd'>;
}
declare module 'web-vitals/dist/web-vitals.iife.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.iife'>;
}
declare module 'web-vitals/dist/web-vitals.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals'>;
}
declare module 'web-vitals/dist/web-vitals.umd.js' {
  declare module.exports: $Exports<'web-vitals/dist/web-vitals.umd'>;
}
