export interface SpaceGroup {
  name: string;
  number: number;
  symopsIncludingCentering: number;
  symopsExcludingCentering: number;
  crystalSystem:
    | 'Triclinic'
    | 'Monoclinic'
    | 'Orthorhombic'
    | 'Tetragonal'
    | 'Trigonal'
    | 'Hexagonal'
    | 'Cubic'
    | undefined;
}

const spaceGroupEquivalents = [
  ['P2', 'P121', 'P112'],
  ['P21', 'P1211', 'P1121'],
  ['C2', 'C121', 'B112'],
];

function getEquivalentNames(name: string) {
  for (const equivalents of spaceGroupEquivalents) {
    for (const group of equivalents) {
      if (name.toUpperCase() === group) return equivalents;
    }
  }
  return [name];
}

export function getSpaceGroup(
  name: string | undefined
): SpaceGroup | undefined {
  if (name === undefined) return undefined;
  const nameWithoutSpaces = name.replace(/\s/g, '').toUpperCase();
  const equivalents = getEquivalentNames(nameWithoutSpaces);
  for (const group of SPACE_GROUPS) {
    if (equivalents.includes(group.name.toUpperCase())) return group;
  }
  return undefined;
}

export const SPACE_GROUPS: readonly SpaceGroup[] = [
  {
    name: 'P1',
    number: 1,
    symopsIncludingCentering: 1,
    symopsExcludingCentering: 1,
    crystalSystem: 'Triclinic',
  },
  {
    name: 'P-1',
    number: 2,
    symopsIncludingCentering: 2,
    symopsExcludingCentering: 2,
    crystalSystem: 'Triclinic',
  },
  {
    name: 'P2',
    number: 3,
    symopsIncludingCentering: 2,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P21',
    number: 4,
    symopsIncludingCentering: 2,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'C2',
    number: 5,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'Pm',
    number: 6,
    symopsIncludingCentering: 2,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'Pc',
    number: 7,
    symopsIncludingCentering: 2,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'Cm',
    number: 8,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'Cc',
    number: 9,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P2/m',
    number: 10,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P21/m',
    number: 11,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'C2/m',
    number: 12,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P2/c',
    number: 13,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P21/c',
    number: 14,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'C2/c',
    number: 15,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P222',
    number: 16,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'P2221',
    number: 17,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'P21212',
    number: 18,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'P212121',
    number: 19,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'C2221',
    number: 20,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'C222',
    number: 21,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'F222',
    number: 22,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'I222',
    number: 23,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'I212121',
    number: 24,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pmm2',
    number: 25,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pmc21',
    number: 26,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pcc2',
    number: 27,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pma2',
    number: 28,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pca21',
    number: 29,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pnc2',
    number: 30,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pmn21',
    number: 31,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pba2',
    number: 32,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pna21',
    number: 33,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pnn2',
    number: 34,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Cmm2',
    number: 35,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Cmc21',
    number: 36,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Ccc2',
    number: 37,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Amm2',
    number: 38,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Abm2',
    number: 39,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Ama2',
    number: 40,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Aba2',
    number: 41,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Fmm2',
    number: 42,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Fdd2',
    number: 43,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Imm2',
    number: 44,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Iba2',
    number: 45,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Ima2',
    number: 46,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pmmm',
    number: 47,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pnnn',
    number: 48,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pccm',
    number: 49,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pban',
    number: 50,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pmma',
    number: 51,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pnna',
    number: 52,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pmna',
    number: 53,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pcca',
    number: 54,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pbam',
    number: 55,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pccn',
    number: 56,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pbcm',
    number: 57,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pnnm',
    number: 58,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pmmn',
    number: 59,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pbcn',
    number: 60,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pbca',
    number: 61,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Pnma',
    number: 62,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Cmcm',
    number: 63,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Cmca',
    number: 64,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Cmmm',
    number: 65,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Cccm',
    number: 66,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Cmma',
    number: 67,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Ccca',
    number: 68,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Fmmm',
    number: 69,
    symopsIncludingCentering: 32,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Fddd',
    number: 70,
    symopsIncludingCentering: 32,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Immm',
    number: 71,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Ibam',
    number: 72,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Ibca',
    number: 73,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'Imma',
    number: 74,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'P4',
    number: 75,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P41',
    number: 76,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42',
    number: 77,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P43',
    number: 78,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I4',
    number: 79,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I41',
    number: 80,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P-4',
    number: 81,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I-4',
    number: 82,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/m',
    number: 83,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/m',
    number: 84,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/n',
    number: 85,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/n',
    number: 86,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I4/m',
    number: 87,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I41/a',
    number: 88,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P422',
    number: 89,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4212',
    number: 90,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4122',
    number: 91,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P41212',
    number: 92,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4222',
    number: 93,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42212',
    number: 94,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4322',
    number: 95,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P43212',
    number: 96,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I422',
    number: 97,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I4122',
    number: 98,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4mm',
    number: 99,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4bm',
    number: 100,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42cm',
    number: 101,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42nm',
    number: 102,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4cc',
    number: 103,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4nc',
    number: 104,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42mc',
    number: 105,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42bc',
    number: 106,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I4mm',
    number: 107,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I4cm',
    number: 108,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I41md',
    number: 109,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I41cd',
    number: 110,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P-42m',
    number: 111,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P-42c',
    number: 112,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P-421m',
    number: 113,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P-421c',
    number: 114,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P-4m2',
    number: 115,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P-4c2',
    number: 116,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P-4b2',
    number: 117,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P-4n2',
    number: 118,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I-4m2',
    number: 119,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I-4c2',
    number: 120,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I-42m',
    number: 121,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I-42d',
    number: 122,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 8,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/mmm',
    number: 123,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/mcc',
    number: 124,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/nbm',
    number: 125,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/nnc',
    number: 126,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/mbm',
    number: 127,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/mnc',
    number: 128,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/nmm',
    number: 129,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P4/ncc',
    number: 130,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/mmc',
    number: 131,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/mcm',
    number: 132,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/nbc',
    number: 133,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/nnm',
    number: 134,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/mbc',
    number: 135,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/mnm',
    number: 136,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/nmc',
    number: 137,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P42/ncm',
    number: 138,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I4/mmm',
    number: 139,
    symopsIncludingCentering: 32,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I4/mcm',
    number: 140,
    symopsIncludingCentering: 32,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I41/amd',
    number: 141,
    symopsIncludingCentering: 32,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'I41/acd',
    number: 142,
    symopsIncludingCentering: 32,
    symopsExcludingCentering: 16,
    crystalSystem: 'Tetragonal',
  },
  {
    name: 'P3',
    number: 143,
    symopsIncludingCentering: 3,
    symopsExcludingCentering: 3,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P31',
    number: 144,
    symopsIncludingCentering: 3,
    symopsExcludingCentering: 3,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P32',
    number: 145,
    symopsIncludingCentering: 3,
    symopsExcludingCentering: 3,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'H3',
    number: 146,
    symopsIncludingCentering: 9,
    symopsExcludingCentering: 3,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'R3',
    number: 1146,
    symopsIncludingCentering: 3,
    symopsExcludingCentering: 3,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P-3',
    number: 147,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'H-3',
    number: 148,
    symopsIncludingCentering: 18,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'R-3',
    number: 1148,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P312',
    number: 149,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P321',
    number: 150,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P3112',
    number: 151,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P3121',
    number: 152,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P3212',
    number: 153,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P3221',
    number: 154,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'H32',
    number: 155,
    symopsIncludingCentering: 18,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'R32',
    number: 1155,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P3m1',
    number: 156,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P31m',
    number: 157,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P3c1',
    number: 158,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P31c',
    number: 159,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'H3m',
    number: 160,
    symopsIncludingCentering: 18,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'R3m',
    number: 1160,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'H3c',
    number: 161,
    symopsIncludingCentering: 18,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'R3c',
    number: 1161,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P-31m',
    number: 162,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P-31c',
    number: 163,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P-3m1',
    number: 164,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P-3c1',
    number: 165,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'H-3m',
    number: 166,
    symopsIncludingCentering: 36,
    symopsExcludingCentering: 12,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'R-3m',
    number: 1166,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'H-3c',
    number: 167,
    symopsIncludingCentering: 36,
    symopsExcludingCentering: 12,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'R-3c',
    number: 1167,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Trigonal',
  },
  {
    name: 'P6',
    number: 168,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P61',
    number: 169,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P65',
    number: 170,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P62',
    number: 171,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P64',
    number: 172,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P63',
    number: 173,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P-6',
    number: 174,
    symopsIncludingCentering: 6,
    symopsExcludingCentering: 6,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6/m',
    number: 175,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P63/m',
    number: 176,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P622',
    number: 177,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6122',
    number: 178,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6522',
    number: 179,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6222',
    number: 180,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6422',
    number: 181,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6322',
    number: 182,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6mm',
    number: 183,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6cc',
    number: 184,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P63cm',
    number: 185,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P63mc',
    number: 186,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P-6m2',
    number: 187,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P-6c2',
    number: 188,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P-62m',
    number: 189,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P-62c',
    number: 190,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6/mmm',
    number: 191,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P6/mcc',
    number: 192,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P63/mcm',
    number: 193,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P63/mmc',
    number: 194,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Hexagonal',
  },
  {
    name: 'P23',
    number: 195,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Cubic',
  },
  {
    name: 'F23',
    number: 196,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 12,
    crystalSystem: 'Cubic',
  },
  {
    name: 'I23',
    number: 197,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 12,
    crystalSystem: 'Cubic',
  },
  {
    name: 'P213',
    number: 198,
    symopsIncludingCentering: 12,
    symopsExcludingCentering: 12,
    crystalSystem: 'Cubic',
  },
  {
    name: 'I213',
    number: 199,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 12,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Pm-3',
    number: 200,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Pn-3',
    number: 201,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Fm-3',
    number: 202,
    symopsIncludingCentering: 96,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Fd-3',
    number: 203,
    symopsIncludingCentering: 96,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Im-3',
    number: 204,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Pa-3',
    number: 205,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Ia-3',
    number: 206,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'P432',
    number: 207,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'P4232',
    number: 208,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'F432',
    number: 209,
    symopsIncludingCentering: 96,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'F4132',
    number: 210,
    symopsIncludingCentering: 96,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'I432',
    number: 211,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'P4332',
    number: 212,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'P4132',
    number: 213,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'I4132',
    number: 214,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'P-43m',
    number: 215,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'F-43m',
    number: 216,
    symopsIncludingCentering: 96,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'I-43m',
    number: 217,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'P-43n',
    number: 218,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'F-43c',
    number: 219,
    symopsIncludingCentering: 96,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'I-43d',
    number: 220,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 24,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Pm-3m',
    number: 221,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Pn-3n',
    number: 222,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Pm-3n',
    number: 223,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Pn-3m',
    number: 224,
    symopsIncludingCentering: 48,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Fm-3m',
    number: 225,
    symopsIncludingCentering: 192,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Fm-3c',
    number: 226,
    symopsIncludingCentering: 192,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Fd-3m',
    number: 227,
    symopsIncludingCentering: 192,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Fd-3c',
    number: 228,
    symopsIncludingCentering: 192,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Im-3m',
    number: 229,
    symopsIncludingCentering: 96,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'Ia-3d',
    number: 230,
    symopsIncludingCentering: 96,
    symopsExcludingCentering: 48,
    crystalSystem: 'Cubic',
  },
  {
    name: 'P112',
    number: 1003,
    symopsIncludingCentering: 2,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P1121',
    number: 1004,
    symopsIncludingCentering: 2,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'B2',
    number: 1005,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: undefined,
  },
  {
    name: 'A2',
    number: 2005,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'C21',
    number: 3005,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: undefined,
  },
  {
    name: 'I2',
    number: 4005,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'I21',
    number: 5005,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: undefined,
  },
  {
    name: 'P11m',
    number: 1006,
    symopsIncludingCentering: 2,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P11b',
    number: 1007,
    symopsIncludingCentering: 2,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'B11m',
    number: 1008,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'B11b',
    number: 1009,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 2,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P112/m',
    number: 1010,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P1121/m',
    number: 1011,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'B112/m',
    number: 1012,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P112/b',
    number: 1013,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P1121/b',
    number: 1014,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P121/n1',
    number: 2014,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P121/a1',
    number: 3014,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'B112/b',
    number: 1015,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: 'Monoclinic',
  },
  {
    name: 'P2122',
    number: 1017,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'P2212',
    number: 2017,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'P21212a',
    number: 1018,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: undefined,
  },
  {
    name: 'P21221',
    number: 2018,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'P22121',
    number: 3018,
    symopsIncludingCentering: 4,
    symopsExcludingCentering: 4,
    crystalSystem: 'Orthorhombic',
  },
  {
    name: 'C2221a',
    number: 1020,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: undefined,
  },
  {
    name: 'C222a',
    number: 1021,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: undefined,
  },
  {
    name: 'F222a',
    number: 1022,
    symopsIncludingCentering: 16,
    symopsExcludingCentering: 4,
    crystalSystem: undefined,
  },
  {
    name: 'I222a',
    number: 1023,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 4,
    crystalSystem: undefined,
  },
  {
    name: 'Pmmn2',
    number: 1059,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: undefined,
  },
  {
    name: 'P42212a',
    number: 1094,
    symopsIncludingCentering: 8,
    symopsExcludingCentering: 8,
    crystalSystem: undefined,
  },
  {
    name: 'I23a',
    number: 1197,
    symopsIncludingCentering: 24,
    symopsExcludingCentering: 12,
    crystalSystem: undefined,
  },
] as const;
