export const LOG_IN = 'LOG_IN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOG_OUT = 'LOG_OUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';

/** SITES */
export const SET_SITE = 'SET_SITE';

/** SITES */
export const SITE_SELECTED = 'SITE_SELECTED';

export const SET_SESSIONS_MX_COLUMNS = 'SET_SESSIONS_MX_COLUMNS';
export const SET_SESSIONS_SAXS_COLUMNS = 'SET_SESSIONS_SAXS_COLUMNS';
export const SET_SESSIONS_EM_COLUMNS = 'SET_SESSIONS_EM_COLUMNS';
