/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Username = string;
export type Action = string;
export type Comments = string;
export type Datetime = string;

export interface AdminActivity {
  username: Username;
  action: Action;
  comments: Comments;
  dateTime: Datetime;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withAdminActivity<TBase extends Constructor>(Base: TBase) {
  return class WithAdminActivity extends Base {
    username: Username;
    action: Action;
    comments: Comments;
    dateTime: Datetime;
  }
}
