/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Plugins = PluginConfig[];

export interface AuthConfig {
  plugins: Plugins;
}
export interface PluginConfig {
  name: Name;
  config: Config;
}
export interface Config {
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withAuthConfig<TBase extends Constructor>(Base: TBase) {
  return class WithAuthConfig extends Base {
    plugins: Plugins;
  }
}
export function withPluginConfig<TBase extends Constructor>(Base: TBase) {
  return class WithPluginConfig extends Base {
    name: Name;
    config: Config;
  }
}
export function withConfig<TBase extends Constructor>(Base: TBase) {
  return class WithConfig extends Base {
  }
}
