import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Errors = number;
export type Warnings = number;
export type Info = number;

export interface AutoProcProgramMessageStatuses {
  statuses: Statuses;
}
export interface Statuses {
  [k: string]: AutoProcProgramMessageStatus;
}
export interface AutoProcProgramMessageStatus {
  errors: Errors;
  warnings: Warnings;
  info: Info;
}


export abstract class AutoProcProgramMessageStatusesBase extends Entity {
  statuses: Statuses;
}

export abstract class AutoProcProgramMessageStatusesSingletonBase extends SingletonEntity {
  statuses: Statuses;
}

export abstract class AutoProcProgramMessageStatusBase extends Entity {
  errors: Errors;
  warnings: Warnings;
  info: Info;
}

export abstract class AutoProcProgramMessageStatusSingletonBase extends SingletonEntity {
  errors: Errors;
  warnings: Warnings;
  info: Info;
}

