import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Autoprocprogramattachmentid = number;
export type Autoprocprogramid = number;
export type Filename = string;
export type Filetype = string;
export type Importancerank = number;
/**
 * Url to autoproc program attachment
 */
export type Url = string;

export interface AutoProcProgramAttachment {
  autoProcProgramAttachmentId: Autoprocprogramattachmentid;
  autoProcProgramId: Autoprocprogramid;
  fileName: Filename;
  fileType: Filetype;
  importanceRank?: Importancerank;
  _metadata: AutoProcProgramAttachmentMetaData;
}
export interface AutoProcProgramAttachmentMetaData {
  url: Url;
}


export abstract class AutoProcProgramAttachmentBase extends Entity {
  autoProcProgramAttachmentId: Autoprocprogramattachmentid;
  autoProcProgramId: Autoprocprogramid;
  fileName: Filename;
  fileType: Filetype;
  importanceRank?: Importancerank;
  _metadata: AutoProcProgramAttachmentMetaData;
}

export abstract class AutoProcProgramAttachmentSingletonBase extends SingletonEntity {
  autoProcProgramAttachmentId: Autoprocprogramattachmentid;
  autoProcProgramId: Autoprocprogramid;
  fileName: Filename;
  fileType: Filetype;
  importanceRank?: Importancerank;
  _metadata: AutoProcProgramAttachmentMetaData;
}

export abstract class AutoProcProgramAttachmentMetaDataBase extends Entity {
  url: Url;
}

export abstract class AutoProcProgramAttachmentMetaDataSingletonBase extends SingletonEntity {
  url: Url;
}

