/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Autoprocprogramattachmentid = number;
export type Autoprocprogramid = number;
export type Filename = string;
export type Filetype = string;
export type Importancerank = number;
/**
 * Url to autoproc program attachment
 */
export type Url = string;

export interface AutoProcProgramAttachment {
  autoProcProgramAttachmentId: Autoprocprogramattachmentid;
  autoProcProgramId: Autoprocprogramid;
  fileName: Filename;
  fileType: Filetype;
  importanceRank?: Importancerank;
  _metadata: AutoProcProgramAttachmentMetaData;
}
export interface AutoProcProgramAttachmentMetaData {
  url: Url;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withAutoProcProgramAttachment<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcProgramAttachment extends Base {
    autoProcProgramAttachmentId: Autoprocprogramattachmentid;
    autoProcProgramId: Autoprocprogramid;
    fileName: Filename;
    fileType: Filetype;
    importanceRank?: Importancerank;
    _metadata: AutoProcProgramAttachmentMetaData;
  }
}
export function withAutoProcProgramAttachmentMetaData<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcProgramAttachmentMetaData extends Base {
    url: Url;
  }
}
