/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Errors = number;
export type Warnings = number;
export type Info = number;

export interface AutoProcProgramMessageStatus {
  errors: Errors;
  warnings: Warnings;
  info: Info;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withAutoProcProgramMessageStatus<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcProgramMessageStatus extends Base {
    errors: Errors;
    warnings: Warnings;
    info: Info;
  }
}
