/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Comments = string;
/**
 * An enumeration.
 */
export type ScalingStatisticsType = "overall" | "innerShell" | "outerShell";
export type Resolutionlimitlow = number;
export type Resolutionlimithigh = number;
export type Rmerge = number;
export type Rmeasalliplusiminus = number;
export type Rpimalliplusiminus = number;
export type Fractionalpartialbias = number;
export type Ntotalobservations = number;
export type Ntotaluniqueobservations = number;
export type Meanioversigi = number;
export type Completeness = number;
export type Multiplicity = number;
export type Anomalouscompleteness = number;
export type Anomalousmultiplicity = number;
export type Anomalous = boolean;
export type Cchalf = number;
export type Ccanomalous = number;
export type Resioversigi2 = number;

export interface AutoProcScalingStatistics {
  comments?: Comments;
  scalingStatisticsType?: ScalingStatisticsType;
  resolutionLimitLow?: Resolutionlimitlow;
  resolutionLimitHigh?: Resolutionlimithigh;
  rMerge?: Rmerge;
  rMeasAllIPlusIMinus?: Rmeasalliplusiminus;
  rPimAllIPlusIMinus?: Rpimalliplusiminus;
  fractionalPartialBias?: Fractionalpartialbias;
  nTotalObservations?: Ntotalobservations;
  nTotalUniqueObservations?: Ntotaluniqueobservations;
  meanIOverSigI?: Meanioversigi;
  completeness?: Completeness;
  multiplicity?: Multiplicity;
  anomalousCompleteness?: Anomalouscompleteness;
  anomalousMultiplicity?: Anomalousmultiplicity;
  anomalous?: Anomalous;
  ccHalf?: Cchalf;
  ccAnomalous?: Ccanomalous;
  resIOverSigI2?: Resioversigi2;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withAutoProcScalingStatistics<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcScalingStatistics extends Base {
    comments?: Comments;
    scalingStatisticsType?: ScalingStatisticsType;
    resolutionLimitLow?: Resolutionlimitlow;
    resolutionLimitHigh?: Resolutionlimithigh;
    rMerge?: Rmerge;
    rMeasAllIPlusIMinus?: Rmeasalliplusiminus;
    rPimAllIPlusIMinus?: Rpimalliplusiminus;
    fractionalPartialBias?: Fractionalpartialbias;
    nTotalObservations?: Ntotalobservations;
    nTotalUniqueObservations?: Ntotaluniqueobservations;
    meanIOverSigI?: Meanioversigi;
    completeness?: Completeness;
    multiplicity?: Multiplicity;
    anomalousCompleteness?: Anomalouscompleteness;
    anomalousMultiplicity?: Anomalousmultiplicity;
    anomalous?: Anomalous;
    ccHalf?: Cchalf;
    ccAnomalous?: Ccanomalous;
    resIOverSigI2?: Resioversigi2;
  }
}
