/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Number of attachments
 */
export type Attachments = number;
export type Autoprocprogrammessageid = number;
export type Autoprocprogramid = number;
export type Description = string;
export type Message = string;
/**
 * An enumeration.
 */
export type AutoProcProgramMessageSeverity = "ERROR" | "WARNING" | "INFO";
export type Recordtimestamp = string;
export type Autoprocprogrammessages = AutoProcProgramMessage[];
export type Imagesweepcount = number;

export interface AutoProcProgramMetadata {
  attachments?: Attachments;
  autoProcProgramMessages?: Autoprocprogrammessages;
  imageSweepCount?: Imagesweepcount;
}
export interface AutoProcProgramMessage {
  autoProcProgramMessageId: Autoprocprogrammessageid;
  autoProcProgramId: Autoprocprogramid;
  description: Description;
  message: Message;
  severity: AutoProcProgramMessageSeverity;
  recordTimeStamp: Recordtimestamp;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withAutoProcProgramMetadata<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcProgramMetadata extends Base {
    attachments?: Attachments;
    autoProcProgramMessages?: Autoprocprogrammessages;
    imageSweepCount?: Imagesweepcount;
  }
}
export function withAutoProcProgramMessage<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcProgramMessage extends Base {
    autoProcProgramMessageId: Autoprocprogrammessageid;
    autoProcProgramId: Autoprocprogramid;
    description: Description;
    message: Message;
    severity: AutoProcProgramMessageSeverity;
    recordTimeStamp: Recordtimestamp;
  }
}
