/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Autoprocprogrammessageid = number;
export type Autoprocprogramid = number;
export type Description = string;
export type Message = string;
/**
 * An enumeration.
 */
export type AutoProcProgramMessageSeverity = "ERROR" | "WARNING" | "INFO";
export type Recordtimestamp = string;

export interface AutoProcProgramMessage {
  autoProcProgramMessageId: Autoprocprogrammessageid;
  autoProcProgramId: Autoprocprogramid;
  description: Description;
  message: Message;
  severity: AutoProcProgramMessageSeverity;
  recordTimeStamp: Recordtimestamp;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withAutoProcProgramMessage<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcProgramMessage extends Base {
    autoProcProgramMessageId: Autoprocprogrammessageid;
    autoProcProgramId: Autoprocprogramid;
    description: Description;
    message: Message;
    severity: AutoProcProgramMessageSeverity;
    recordTimeStamp: Recordtimestamp;
  }
}
