/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Refinedxbeam = number;
export type Refinedybeam = number;
export type Spacegroup = string;
export type RefinedcellA = number;
export type RefinedcellB = number;
export type RefinedcellC = number;
export type RefinedcellAlpha = number;
export type RefinedcellBeta = number;
export type RefinedcellGamma = number;
export type Comments = string;
/**
 * An enumeration.
 */
export type ScalingStatisticsType = "overall" | "innerShell" | "outerShell";
export type Resolutionlimitlow = number;
export type Resolutionlimithigh = number;
export type Rmerge = number;
export type Rmeasalliplusiminus = number;
export type Rpimalliplusiminus = number;
export type Fractionalpartialbias = number;
export type Ntotalobservations = number;
export type Ntotaluniqueobservations = number;
export type Meanioversigi = number;
export type Completeness = number;
export type Multiplicity = number;
export type Anomalouscompleteness = number;
export type Anomalousmultiplicity = number;
export type Anomalous = boolean;
export type Cchalf = number;
export type Ccanomalous = number;
export type Resioversigi2 = number;
export type Autoprocscalingstatistics = AutoProcScalingStatistics[];
export type Autoprocscalinghasint = AutoProcScalingHasInt[];
export type Xbeam = number;
export type Ybeam = number;

export interface AutoProcIntegration {
  refinedXBeam?: Refinedxbeam;
  refinedYBeam?: Refinedybeam;
  AutoProcScalingHasInt?: Autoprocscalinghasint;
  DataCollection?: AutoProcIntegrationDataCollection;
}
export interface AutoProcScalingHasInt {
  AutoProcScaling?: AutoProcScaling;
}
export interface AutoProcScaling {
  AutoProc?: AutoProc;
  AutoProcScalingStatistics?: Autoprocscalingstatistics;
}
export interface AutoProc {
  spaceGroup: Spacegroup;
  refinedCell_a: RefinedcellA;
  refinedCell_b: RefinedcellB;
  refinedCell_c: RefinedcellC;
  refinedCell_alpha: RefinedcellAlpha;
  refinedCell_beta: RefinedcellBeta;
  refinedCell_gamma: RefinedcellGamma;
}
export interface AutoProcScalingStatistics {
  comments?: Comments;
  scalingStatisticsType?: ScalingStatisticsType;
  resolutionLimitLow?: Resolutionlimitlow;
  resolutionLimitHigh?: Resolutionlimithigh;
  rMerge?: Rmerge;
  rMeasAllIPlusIMinus?: Rmeasalliplusiminus;
  rPimAllIPlusIMinus?: Rpimalliplusiminus;
  fractionalPartialBias?: Fractionalpartialbias;
  nTotalObservations?: Ntotalobservations;
  nTotalUniqueObservations?: Ntotaluniqueobservations;
  meanIOverSigI?: Meanioversigi;
  completeness?: Completeness;
  multiplicity?: Multiplicity;
  anomalousCompleteness?: Anomalouscompleteness;
  anomalousMultiplicity?: Anomalousmultiplicity;
  anomalous?: Anomalous;
  ccHalf?: Cchalf;
  ccAnomalous?: Ccanomalous;
  resIOverSigI2?: Resioversigi2;
}
export interface AutoProcIntegrationDataCollection {
  xBeam?: Xbeam;
  yBeam?: Ybeam;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withAutoProcIntegration<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcIntegration extends Base {
    refinedXBeam?: Refinedxbeam;
    refinedYBeam?: Refinedybeam;
    AutoProcScalingHasInt?: Autoprocscalinghasint;
    DataCollection?: AutoProcIntegrationDataCollection;
  }
}
export function withAutoProcScalingHasInt<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcScalingHasInt extends Base {
    AutoProcScaling?: AutoProcScaling;
  }
}
export function withAutoProcScaling<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcScaling extends Base {
    AutoProc?: AutoProc;
    AutoProcScalingStatistics?: Autoprocscalingstatistics;
  }
}
export function withAutoProc<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProc extends Base {
    spaceGroup: Spacegroup;
    refinedCell_a: RefinedcellA;
    refinedCell_b: RefinedcellB;
    refinedCell_c: RefinedcellC;
    refinedCell_alpha: RefinedcellAlpha;
    refinedCell_beta: RefinedcellBeta;
    refinedCell_gamma: RefinedcellGamma;
  }
}
export function withAutoProcScalingStatistics<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcScalingStatistics extends Base {
    comments?: Comments;
    scalingStatisticsType?: ScalingStatisticsType;
    resolutionLimitLow?: Resolutionlimitlow;
    resolutionLimitHigh?: Resolutionlimithigh;
    rMerge?: Rmerge;
    rMeasAllIPlusIMinus?: Rmeasalliplusiminus;
    rPimAllIPlusIMinus?: Rpimalliplusiminus;
    fractionalPartialBias?: Fractionalpartialbias;
    nTotalObservations?: Ntotalobservations;
    nTotalUniqueObservations?: Ntotaluniqueobservations;
    meanIOverSigI?: Meanioversigi;
    completeness?: Completeness;
    multiplicity?: Multiplicity;
    anomalousCompleteness?: Anomalouscompleteness;
    anomalousMultiplicity?: Anomalousmultiplicity;
    anomalous?: Anomalous;
    ccHalf?: Cchalf;
    ccAnomalous?: Ccanomalous;
    resIOverSigI2?: Resioversigi2;
  }
}
export function withAutoProcIntegrationDataCollection<TBase extends Constructor>(Base: TBase) {
  return class WithAutoProcIntegrationDataCollection extends Base {
    xBeam?: Xbeam;
    yBeam?: Ybeam;
  }
}
