/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Unit = string;
export type Data = unknown[];

export interface BreakdownPlottable {
  title: Title;
  unit?: Unit;
  data: Data;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withBreakdownPlottable<TBase extends Constructor>(Base: TBase) {
  return class WithBreakdownPlottable extends Base {
    title: Title;
    unit?: Unit;
    data: Data;
  }
}
