/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Eventtype = string;
export type Starttime = string;
export type Endtime = string;
export type Protein = string;
export type Sample = string;
export type Subtype = string;
export type Status = string;
export type Title = string;
export type Session = string;
export type Sessionid = string;

export interface BreakdownPoint {
  eventType: Eventtype;
  startTime: Starttime;
  endTime: Endtime;
  protein?: Protein;
  sample?: Sample;
  subType?: Subtype;
  status?: Status;
  title?: Title;
  session?: Session;
  sessionId?: Sessionid;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withBreakdownPoint<TBase extends Constructor>(Base: TBase) {
  return class WithBreakdownPoint extends Base {
    eventType: Eventtype;
    startTime: Starttime;
    endTime: Endtime;
    protein?: Protein;
    sample?: Sample;
    subType?: Subtype;
    status?: Status;
    title?: Title;
    session?: Session;
    sessionId?: Sessionid;
  }
}
