import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Composition = null | string;
export type Name1 = string;
export type Id = number;
export type Componentid = number;

export interface Component {
  name: Name;
  composition?: Composition;
  ComponentType: ComponentType;
  componentId: Componentid;
}
export interface ComponentType {
  name: Name1;
  componentTypeId: Id;
}


export abstract class ComponentBase extends Entity {
  name: Name;
  composition?: Composition;
  ComponentType: ComponentType;
  componentId: Componentid;
}

export abstract class ComponentSingletonBase extends SingletonEntity {
  name: Name;
  composition?: Composition;
  ComponentType: ComponentType;
  componentId: Componentid;
}

export abstract class ComponentTypeBase extends Entity {
  name: Name1;
  componentTypeId: Id;
}

export abstract class ComponentTypeSingletonBase extends SingletonEntity {
  name: Name1;
  componentTypeId: Id;
}

