/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Componentid = number;
export type Componenttypeid = number;
export type Proposalid = number;
export type Name = string;
export type Composition = string;
export type Concentration = number;
export type Componenttypeid1 = number;
export type Name1 = string;

export interface ComponentResponse {
  componentId: Componentid;
  componentTypeId: Componenttypeid;
  proposalId?: Proposalid;
  name: Name;
  composition?: Composition;
  concentration?: Concentration;
  ComponentType: ComponentType;
}
export interface ComponentType {
  componentTypeId: Componenttypeid1;
  name: Name1;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withComponentResponse<TBase extends Constructor>(Base: TBase) {
  return class WithComponentResponse extends Base {
    componentId: Componentid;
    componentTypeId: Componenttypeid;
    proposalId?: Proposalid;
    name: Name;
    composition?: Composition;
    concentration?: Concentration;
    ComponentType: ComponentType;
  }
}
export function withComponentType<TBase extends Constructor>(Base: TBase) {
  return class WithComponentType extends Base {
    componentTypeId: Componenttypeid1;
    name: Name1;
  }
}
