/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Composition = string;
export type Concentration = number;

export interface Component {
  name: Name;
  composition?: Composition;
  concentration?: Concentration;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withComponent<TBase extends Constructor>(Base: TBase) {
  return class WithComponent extends Base {
    name: Name;
    composition?: Composition;
    concentration?: Concentration;
  }
}
