/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Composition1 = string;
export type Concentration = number;
export type Name1 = string;
export type Abundance = number;
export type Ratio = number;
export type Ph = number;

export interface Composition {
  Component: Component;
  abundance?: Abundance;
  ratio?: Ratio;
  ph?: Ph;
}
export interface Component {
  name: Name;
  composition?: Composition1;
  concentration?: Concentration;
  ComponentType: ComponentType;
}
export interface ComponentType {
  name: Name1;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withComposition<TBase extends Constructor>(Base: TBase) {
  return class WithComposition extends Base {
    Component: Component;
    abundance?: Abundance;
    ratio?: Ratio;
    ph?: Ph;
  }
}
export function withComponent<TBase extends Constructor>(Base: TBase) {
  return class WithComponent extends Base {
    name: Name;
    composition?: Composition1;
    concentration?: Concentration;
    ComponentType: ComponentType;
  }
}
export function withComponentType<TBase extends Constructor>(Base: TBase) {
  return class WithComponentType extends Base {
    name: Name1;
  }
}
