/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Componentid = number;
export type Name = string;
export type Composition = null | string;
export type Name1 = string;

export interface ComponentCreateUpdate {
  componentId?: Componentid;
  name: Name;
  composition?: Composition;
  ComponentType: ComponentType;
}
export interface ComponentType {
  name: Name1;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withComponentCreateUpdate<TBase extends Constructor>(Base: TBase) {
  return class WithComponentCreateUpdate extends Base {
    componentId?: Componentid;
    name: Name;
    composition?: Composition;
    ComponentType: ComponentType;
  }
}
export function withComponentType<TBase extends Constructor>(Base: TBase) {
  return class WithComponentType extends Base {
    name: Name1;
  }
}
