/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Dewarid = number;
export type Containertype = string;
/**
 * Position in sample change
 */
export type Samplechangerlocation = string;
/**
 * Beamline if container is assigned
 */
export type Beamlinelocation = string;
export type Containerid = number;
export type Name1 = string;
export type Proposalid = number;
export type Name2 = string;

export interface Container {
  code: Name;
  dewarId: Dewarid;
  containerType: Containertype;
  sampleChangerLocation?: Samplechangerlocation;
  beamlineLocation?: Beamlinelocation;
  containerId: Containerid;
  Dewar: ContainerDewar;
}
export interface ContainerDewar {
  code: Name1;
  Shipping: DewarShipping;
}
export interface DewarShipping {
  proposalId: Proposalid;
  shippingName: Name2;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withContainer<TBase extends Constructor>(Base: TBase) {
  return class WithContainer extends Base {
    code: Name;
    dewarId: Dewarid;
    containerType: Containertype;
    sampleChangerLocation?: Samplechangerlocation;
    beamlineLocation?: Beamlinelocation;
    containerId: Containerid;
    Dewar: ContainerDewar;
  }
}
export function withContainerDewar<TBase extends Constructor>(Base: TBase) {
  return class WithContainerDewar extends Base {
    code: Name1;
    Shipping: DewarShipping;
  }
}
export function withDewarShipping<TBase extends Constructor>(Base: TBase) {
  return class WithDewarShipping extends Base {
    proposalId: Proposalid;
    shippingName: Name2;
  }
}
