/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Diffractionplanid = number;
export type Recordtimestamp = string;

export interface ContainerQueueDiffractionPlan {
  diffractionPlanId: Diffractionplanid;
  recordTimeStamp: Recordtimestamp;
  scanParameters?: Scanparameters;
}
export interface Scanparameters {
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withContainerQueueDiffractionPlan<TBase extends Constructor>(Base: TBase) {
  return class WithContainerQueueDiffractionPlan extends Base {
    diffractionPlanId: Diffractionplanid;
    recordTimeStamp: Recordtimestamp;
    scanParameters?: Scanparameters;
  }
}
export function withScanparameters<TBase extends Constructor>(Base: TBase) {
  return class WithScanparameters extends Base {
  }
}
