/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Dewarid = number;
export type Containertype = string;
/**
 * Position in sample change
 */
export type Samplechangerlocation = string;
/**
 * Beamline if container is assigned
 */
export type Beamlinelocation = string;

export interface ContainerCreate {
  code: Name;
  dewarId: Dewarid;
  containerType: Containertype;
  sampleChangerLocation?: Samplechangerlocation;
  beamlineLocation?: Beamlinelocation;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withContainerCreate<TBase extends Constructor>(Base: TBase) {
  return class WithContainerCreate extends Base {
    code: Name;
    dewarId: Dewarid;
    containerType: Containertype;
    sampleChangerLocation?: Samplechangerlocation;
    beamlineLocation?: Beamlinelocation;
  }
}
