/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Proteinid = number;

export interface CrystalProteinCreate {
  proteinId: Proteinid;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withCrystalProteinCreate<TBase extends Constructor>(Base: TBase) {
  return class WithCrystalProteinCreate extends Base {
    proteinId: Proteinid;
  }
}
