/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Crystalcompositionid = number;
export type Componentid = number;
export type Crystalid = number;
export type Concentrationtypeid = number;
export type Abundance = number;
export type Ratio = number;
export type Ph = number;
export type Componentid1 = number;
export type Componenttypeid = number;
export type Proposalid = number;
export type Name = string;
export type Composition = string;
export type Concentration = number;
export type Componenttypeid1 = number;
export type Name1 = string;

export interface CrystalCompositionResponse {
  crystalCompositionId: Crystalcompositionid;
  componentId: Componentid;
  crystalId: Crystalid;
  concentrationTypeId?: Concentrationtypeid;
  abundance?: Abundance;
  ratio?: Ratio;
  ph?: Ph;
  Component: ComponentResponse;
}
export interface ComponentResponse {
  componentId: Componentid1;
  componentTypeId: Componenttypeid;
  proposalId?: Proposalid;
  name: Name;
  composition?: Composition;
  concentration?: Concentration;
  ComponentType: ComponentType;
}
export interface ComponentType {
  componentTypeId: Componenttypeid1;
  name: Name1;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withCrystalCompositionResponse<TBase extends Constructor>(Base: TBase) {
  return class WithCrystalCompositionResponse extends Base {
    crystalCompositionId: Crystalcompositionid;
    componentId: Componentid;
    crystalId: Crystalid;
    concentrationTypeId?: Concentrationtypeid;
    abundance?: Abundance;
    ratio?: Ratio;
    ph?: Ph;
    Component: ComponentResponse;
  }
}
export function withComponentResponse<TBase extends Constructor>(Base: TBase) {
  return class WithComponentResponse extends Base {
    componentId: Componentid1;
    componentTypeId: Componenttypeid;
    proposalId?: Proposalid;
    name: Name;
    composition?: Composition;
    concentration?: Concentration;
    ComponentType: ComponentType;
  }
}
export function withComponentType<TBase extends Constructor>(Base: TBase) {
  return class WithComponentType extends Base {
    componentTypeId: Componenttypeid1;
    name: Name1;
  }
}
