/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Url to data collection file attachment
 */
export type Url = string;
/**
 * File name
 */
export type Filename = string;

export interface DataCollectionFileAttachmentMetaData {
  url: Url;
  fileName: Filename;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withDataCollectionFileAttachmentMetaData<TBase extends Constructor>(Base: TBase) {
  return class WithDataCollectionFileAttachmentMetaData extends Base {
    url: Url;
    fileName: Filename;
  }
}
