/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Movie = number;
export type Motioncorrection = number;
export type Ctf = number;

export interface EMProcessingStatus {
  movie: Movie;
  motionCorrection: Motioncorrection;
  ctf: Ctf;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withEMProcessingStatus<TBase extends Constructor>(Base: TBase) {
  return class WithEMProcessingStatus extends Base {
    movie: Movie;
    motionCorrection: Motioncorrection;
    ctf: Ctf;
  }
}
