/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Energyscanid = number;

export interface EnergyScan {
  energyScanId: Energyscanid;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withEnergyScan<TBase extends Constructor>(Base: TBase) {
  return class WithEnergyScan extends Base {
    energyScanId: Energyscanid;
  }
}
