import { Entity } from '@rest-hooks/rest';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Eventtypename = string;
export type Eventtype = string;

export interface EventType {
  eventTypeName: Eventtypename;
  eventType: Eventtype;
}

export abstract class EventTypeBase extends Entity {
  eventTypeName: Eventtypename;
  eventType: Eventtype;
}
