/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Type = "XrayDetection" | "XrayExposure" | "LaserExcitation" | "ReactionTrigger";
export type Name1 = string;
export type Offset = number;
export type Duration = number;
export type Period = number;
export type Repetition = number;
export type Events = EventCreate[];

export interface EventChainCreate {
  name?: Name;
  events: Events;
}
export interface EventCreate {
  type: Type;
  name?: Name1;
  offset: Offset;
  duration?: Duration;
  period?: Period;
  repetition?: Repetition;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withEventChainCreate<TBase extends Constructor>(Base: TBase) {
  return class WithEventChainCreate extends Base {
    name?: Name;
    events: Events;
  }
}
export function withEventCreate<TBase extends Constructor>(Base: TBase) {
  return class WithEventCreate extends Base {
    type: Type;
    name?: Name1;
    offset: Offset;
    duration?: Duration;
    period?: Period;
    repetition?: Repetition;
  }
}
