/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ExperimentType = string;
export type TotalDataCollections = number;
export type FailedDataCollections = number;
export type Failedpercent = number;
export type AbortedDataCollections = number;
export type Abortedpercent = number;
export type FrequencyOfThisErrorMessage = number;
export type TheErrorMessage = string;
export type ErrorMessages = ExperimentTypeMessages[];

export interface ExperimentTypeGroup {
  experimentType: ExperimentType;
  total: TotalDataCollections;
  failed: FailedDataCollections;
  failedPercent?: Failedpercent;
  aborted: AbortedDataCollections;
  abortedPercent?: Abortedpercent;
  messages: ErrorMessages;
}
export interface ExperimentTypeMessages {
  count: FrequencyOfThisErrorMessage;
  message: TheErrorMessage;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withExperimentTypeGroup<TBase extends Constructor>(Base: TBase) {
  return class WithExperimentTypeGroup extends Base {
    experimentType: ExperimentType;
    total: TotalDataCollections;
    failed: FailedDataCollections;
    failedPercent?: Failedpercent;
    aborted: AbortedDataCollections;
    abortedPercent?: Abortedpercent;
    messages: ErrorMessages;
  }
}
export function withExperimentTypeMessages<TBase extends Constructor>(Base: TBase) {
  return class WithExperimentTypeMessages extends Base {
    count: FrequencyOfThisErrorMessage;
    message: TheErrorMessage;
  }
}
