/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Graphdataid = number;
export type Graphid = number;
export type X = number;
export type Y = number;

export interface GraphDataResponse {
  graphDataId: Graphdataid;
  graphId: Graphid;
  x: X;
  y: Y;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withGraphDataResponse<TBase extends Constructor>(Base: TBase) {
  return class WithGraphDataResponse extends Base {
    graphDataId: Graphdataid;
    graphId: Graphid;
    x: X;
    y: Y;
  }
}
