/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Graphid = number;
export type Datacollectionid = number;
export type Name = string;

export interface GraphResponse {
  graphId: Graphid;
  dataCollectionId: Datacollectionid;
  name: Name;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withGraphResponse<TBase extends Constructor>(Base: TBase) {
  return class WithGraphResponse extends Base {
    graphId: Graphid;
    dataCollectionId: Datacollectionid;
    name: Name;
  }
}
