import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Values = number[];
export type Bins = number[];
export type Shape = unknown[];
export type Max = number;

export interface ImageHistogram {
  values: Values;
  bins: Bins;
  shape: Shape;
  max: Max;
}


export abstract class ImageHistogramBase extends Entity {
  values: Values;
  bins: Bins;
  shape: Shape;
  max: Max;
}

export abstract class ImageHistogramSingletonBase extends SingletonEntity {
  values: Values;
  bins: Bins;
  shape: Shape;
  max: Max;
}

