/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Proposalid = number;
/**
 * The name for this lab contact
 */
export type CardName = string;
export type CourrierCompany = null | string;
export type AccountNo = null | string;
export type BillingReference = null | string;
export type AvgCustomsValue = number;
export type AvgTransportValue = number;
export type Person = PersonCreate;
export type FirstName = string;
export type Surname = string;
export type EmailAddress = null | string;
export type PhoneNumber = null | string;
export type Laboratory = LaboratoryCreate;
/**
 * The Laboratory name
 */
export type LaboratoryName = string;
/**
 * The Laboratory Address
 */
export type Address = string;
/**
 * The Laboratory City
 */
export type City = string;
/**
 * The Laboratory Country
 */
export type Country = string;
/**
 * The Laboratory optional URL
 */
export type URL = null | string;
/**
 * External Id from the User Portal
 */
export type LaboratoryExtPk = null | number;

export interface LabContactCreate {
  proposalId: Proposalid;
  cardName: CardName;
  defaultCourrierCompany?: CourrierCompany;
  courierAccount?: AccountNo;
  billingReference?: BillingReference;
  dewarAvgCustomsValue?: AvgCustomsValue;
  dewarAvgTransportValue?: AvgTransportValue;
  Person: Person;
}
export interface PersonCreate {
  givenName: FirstName;
  familyName: Surname;
  emailAddress?: EmailAddress;
  phoneNumber?: PhoneNumber;
  Laboratory?: Laboratory;
}
export interface LaboratoryCreate {
  name: LaboratoryName;
  address: Address;
  city: City;
  country: Country;
  url?: URL;
  laboratoryExtPk?: LaboratoryExtPk;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withLabContactCreate<TBase extends Constructor>(Base: TBase) {
  return class WithLabContactCreate extends Base {
    proposalId: Proposalid;
    cardName: CardName;
    defaultCourrierCompany?: CourrierCompany;
    courierAccount?: AccountNo;
    billingReference?: BillingReference;
    dewarAvgCustomsValue?: AvgCustomsValue;
    dewarAvgTransportValue?: AvgTransportValue;
    Person: Person;
  }
}
export function withPersonCreate<TBase extends Constructor>(Base: TBase) {
  return class WithPersonCreate extends Base {
    givenName: FirstName;
    familyName: Surname;
    emailAddress?: EmailAddress;
    phoneNumber?: PhoneNumber;
    Laboratory?: Laboratory;
  }
}
export function withLaboratoryCreate<TBase extends Constructor>(Base: TBase) {
  return class WithLaboratoryCreate extends Base {
    name: LaboratoryName;
    address: Address;
    city: City;
    country: Country;
    url?: URL;
    laboratoryExtPk?: LaboratoryExtPk;
  }
}
