/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cardname = string;
export type Defaultcourriercompany = string;
export type Courieraccount = string;
export type Billingreference = string;
export type Dewaravgcustomsvalue = number;
export type Dewaravgtransportvalue = number;
export type Familyname = string;
export type Emailaddress = string;
export type Phonenumber = string;
export type Name = string;
export type Address = string;
export type City = string;
export type Country = string;
export type Url = string;

export interface LabContactCreateOptional {
  cardName?: Cardname;
  defaultCourrierCompany?: Defaultcourriercompany;
  courierAccount?: Courieraccount;
  billingReference?: Billingreference;
  dewarAvgCustomsValue?: Dewaravgcustomsvalue;
  dewarAvgTransportValue?: Dewaravgtransportvalue;
  Person?: PersonCreateOptional;
}
export interface PersonCreateOptional {
  familyName?: Familyname;
  emailAddress?: Emailaddress;
  phoneNumber?: Phonenumber;
  Laboratory?: LaboratoryCreateOptional;
}
export interface LaboratoryCreateOptional {
  name?: Name;
  address?: Address;
  city?: City;
  country?: Country;
  url?: Url;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withLabContactCreateOptional<TBase extends Constructor>(Base: TBase) {
  return class WithLabContactCreateOptional extends Base {
    cardName?: Cardname;
    defaultCourrierCompany?: Defaultcourriercompany;
    courierAccount?: Courieraccount;
    billingReference?: Billingreference;
    dewarAvgCustomsValue?: Dewaravgcustomsvalue;
    dewarAvgTransportValue?: Dewaravgtransportvalue;
    Person?: PersonCreateOptional;
  }
}
export function withPersonCreateOptional<TBase extends Constructor>(Base: TBase) {
  return class WithPersonCreateOptional extends Base {
    familyName?: Familyname;
    emailAddress?: Emailaddress;
    phoneNumber?: Phonenumber;
    Laboratory?: LaboratoryCreateOptional;
  }
}
export function withLaboratoryCreateOptional<TBase extends Constructor>(Base: TBase) {
  return class WithLaboratoryCreateOptional extends Base {
    name?: Name;
    address?: Address;
    city?: City;
    country?: Country;
    url?: Url;
  }
}
