/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Plugin = string;
export type Login1 = string;
export type Password = string;
export type Token = string;

export interface Login {
  plugin?: Plugin;
  login?: Login1;
  password?: Password;
  token?: Token;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withLogin<TBase extends Constructor>(Base: TBase) {
  return class WithLogin extends Base {
    plugin?: Plugin;
    login?: Login1;
    password?: Password;
    token?: Token;
  }
}
