/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Xrffluorescencemappingid = number;
export type Hist = number[];
export type Bins = number[];
export type Width = number[];

export interface MapHistogram {
  xrfFluorescenceMappingId: Xrffluorescencemappingid;
  hist: Hist;
  bins: Bins;
  width: Width;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withMapHistogram<TBase extends Constructor>(Base: TBase) {
  return class WithMapHistogram extends Base {
    xrfFluorescenceMappingId: Xrffluorescencemappingid;
    hist: Hist;
    bins: Bins;
    width: Width;
  }
}
