/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Xrffluorescencemappingid = number;
export type X = number;
export type Y = number;
export type Value = number;

export interface MapPixelValue {
  xrfFluorescenceMappingId: Xrffluorescencemappingid;
  x: X;
  y: Y;
  value: Value;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withMapPixelValue<TBase extends Constructor>(Base: TBase) {
  return class WithMapPixelValue extends Base {
    xrfFluorescenceMappingId: Xrffluorescencemappingid;
    x: X;
    y: Y;
    value: Value;
  }
}
