/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Xrffluorescencemappingroiid = number;
export type Element = string;
export type Edge = string;
export type Scalar = string;
export type Startenergy = number;
export type Endenergy = number;

export interface MapROI {
  xrfFluorescenceMappingROIId: Xrffluorescencemappingroiid;
  element?: Element;
  edge?: Edge;
  scalar?: Scalar;
  startEnergy: Startenergy;
  endEnergy: Endenergy;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withMapROI<TBase extends Constructor>(Base: TBase) {
  return class WithMapROI extends Base {
    xrfFluorescenceMappingROIId: Xrffluorescencemappingroiid;
    element?: Element;
    edge?: Edge;
    scalar?: Scalar;
    startEnergy: Startenergy;
    endEnergy: Endenergy;
  }
}
