import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The url to sign
 */
export type Validity = string;
export type Token = string;

export interface OneTimeToken {
  validity: Validity;
  token?: Token;
}


export abstract class OneTimeTokenBase extends Entity {
  validity: Validity;
  token?: Token;
}

export abstract class OneTimeTokenSingletonBase extends SingletonEntity {
  validity: Validity;
  token?: Token;
}

