import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Datacollectionid = number;
/**
 * Scan point
 */
export type Imagenumber = number[];
/**
 * Total signal
 */
export type Totalintegratedsignal = number[];
/**
 * Number of spots
 */
export type Goodbraggcandidates = number[];
/**
 * Estimated resolution
 */
export type Method2Res = number[];

export interface PerImageAnalysis {
  dataCollectionId?: Datacollectionid;
  imageNumber?: Imagenumber;
  totalIntegratedSignal?: Totalintegratedsignal;
  goodBraggCandidates?: Goodbraggcandidates;
  method2Res?: Method2Res;
}


export abstract class PerImageAnalysisBase extends Entity {
  dataCollectionId?: Datacollectionid;
  imageNumber?: Imagenumber;
  totalIntegratedSignal?: Totalintegratedsignal;
  goodBraggCandidates?: Goodbraggcandidates;
  method2Res?: Method2Res;
}

export abstract class PerImageAnalysisSingletonBase extends SingletonEntity {
  dataCollectionId?: Datacollectionid;
  imageNumber?: Imagenumber;
  totalIntegratedSignal?: Totalintegratedsignal;
  goodBraggCandidates?: Goodbraggcandidates;
  method2Res?: Method2Res;
}

