/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Role =
  | "Local Contact"
  | "Local Contact 2"
  | "Staff"
  | "Team Leader"
  | "Co-Investigator"
  | "Principal Investigator"
  | "Alternate Contact";
export type Remote = number;

export interface PersonSessionOptions {
  role?: Role;
  remote?: Remote;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withPersonSessionOptions<TBase extends Constructor>(Base: TBase) {
  return class WithPersonSessionOptions extends Base {
    role?: Role;
    remote?: Remote;
  }
}
