/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Posx = number;
export type Posy = number;

export interface Position {
  posX: Posx;
  posY: Posy;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withPosition<TBase extends Constructor>(Base: TBase) {
  return class WithPosition extends Base {
    posX: Posx;
    posY: Posy;
  }
}
