/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Processingjobid = number;
export type Displayname = string;
export type Comments = string;
export type Recordtimestamp = string;
export type Recipe = string;
export type Automatic = boolean;
export type Parameterkey = string;
export type Parametervalue = string;
export type Processingjobparameters = ProcessingJobParameter[];

export interface ProcessingJob {
  processingJobId: Processingjobid;
  displayName?: Displayname;
  comments?: Comments;
  recordTimestamp: Recordtimestamp;
  recipe?: Recipe;
  automatic: Automatic;
  ProcessingJobParameters?: Processingjobparameters;
}
export interface ProcessingJobParameter {
  parameterKey: Parameterkey;
  parameterValue: Parametervalue;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withProcessingJob<TBase extends Constructor>(Base: TBase) {
  return class WithProcessingJob extends Base {
    processingJobId: Processingjobid;
    displayName?: Displayname;
    comments?: Comments;
    recordTimestamp: Recordtimestamp;
    recipe?: Recipe;
    automatic: Automatic;
    ProcessingJobParameters?: Processingjobparameters;
  }
}
export function withProcessingJobParameter<TBase extends Constructor>(Base: TBase) {
  return class WithProcessingJobParameter extends Base {
    parameterKey: Parameterkey;
    parameterValue: Parametervalue;
  }
}
