/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An enumeration.
 */
export type StatusEnum = null | 0 | 1 | 2;

export interface ProcessingStatus {
  status?: StatusEnum;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withProcessingStatus<TBase extends Constructor>(Base: TBase) {
  return class WithProcessingStatus extends Base {
    status?: StatusEnum;
  }
}
