import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An enumeration.
 */
export type StatusEnum = null | 0 | 1 | 2;
export type Autoprocprogramid = number;
export type Movie = number;
export type Motioncorrection = number;
export type Ctf = number;

export interface ProcessingStatusesList {
  statuses: Statuses;
}
export interface Statuses {
  [k: string]: ProcessingStatuses;
}
export interface ProcessingStatuses {
  screening?: Screening;
  xrc?: Xrc;
  processing?: Processing;
  autoIntegration?: Autointegration;
  em?: EMProcessingStatus;
}
export interface Screening {
  [k: string]: ScreeningProcesingStatus[];
}
export interface ScreeningProcesingStatus {
  status?: StatusEnum;
  indexingSuccess: StatusEnum;
}
export interface Xrc {
  [k: string]: ProcessingStatus[];
}
export interface ProcessingStatus {
  status?: StatusEnum;
}
export interface Processing {
  [k: string]: ProcessingProcessingStatus[];
}
export interface ProcessingProcessingStatus {
  status?: StatusEnum;
  autoProcProgramId: Autoprocprogramid;
}
export interface Autointegration {
  [k: string]: ProcessingProcessingStatus[];
}
export interface EMProcessingStatus {
  movie: Movie;
  motionCorrection: Motioncorrection;
  ctf: Ctf;
}


export abstract class ProcessingStatusesListBase extends Entity {
  statuses: Statuses;
}

export abstract class ProcessingStatusesListSingletonBase extends SingletonEntity {
  statuses: Statuses;
}

export abstract class ProcessingStatusesBase extends Entity {
  screening?: Screening;
  xrc?: Xrc;
  processing?: Processing;
  autoIntegration?: Autointegration;
  em?: EMProcessingStatus;
}

export abstract class ProcessingStatusesSingletonBase extends SingletonEntity {
  screening?: Screening;
  xrc?: Xrc;
  processing?: Processing;
  autoIntegration?: Autointegration;
  em?: EMProcessingStatus;
}

export abstract class ScreeningProcesingStatusBase extends Entity {
  status?: StatusEnum;
  indexingSuccess: StatusEnum;
}

export abstract class ScreeningProcesingStatusSingletonBase extends SingletonEntity {
  status?: StatusEnum;
  indexingSuccess: StatusEnum;
}

export abstract class ProcessingStatusBase extends Entity {
  status?: StatusEnum;
}

export abstract class ProcessingStatusSingletonBase extends SingletonEntity {
  status?: StatusEnum;
}

export abstract class ProcessingProcessingStatusBase extends Entity {
  status?: StatusEnum;
  autoProcProgramId: Autoprocprogramid;
}

export abstract class ProcessingProcessingStatusSingletonBase extends SingletonEntity {
  status?: StatusEnum;
  autoProcProgramId: Autoprocprogramid;
}

export abstract class EMProcessingStatusBase extends Entity {
  movie: Movie;
  motionCorrection: Motioncorrection;
  ctf: Ctf;
}

export abstract class EMProcessingStatusSingletonBase extends SingletonEntity {
  movie: Movie;
  motionCorrection: Motioncorrection;
  ctf: Ctf;
}

