/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Number of attached pdbs
 */
export type Pdbs = number;
/**
 * Number of child crystals
 */
export type Crystals = number;
/**
 * Number of child samples
 */
export type Samples = number;
/**
 * Number of data collections
 */
export type Datacollections = number;

export interface ProteinMetaData {
  pdbs?: Pdbs;
  crystals?: Crystals;
  samples?: Samples;
  datacollections?: Datacollections;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withProteinMetaData<TBase extends Constructor>(Base: TBase) {
  return class WithProteinMetaData extends Base {
    pdbs?: Pdbs;
    crystals?: Crystals;
    samples?: Samples;
    datacollections?: Datacollections;
  }
}
