/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Eventtypeid = number;
export type Name = string;

export interface EventType {
  eventTypeId: Eventtypeid;
  name: Name;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withEventType<TBase extends Constructor>(Base: TBase) {
  return class WithEventType extends Base {
    eventTypeId: Eventtypeid;
    name: Name;
  }
}
