/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Proteinid = number;
export type Proposalid = number;
export type Name = string;
export type Acronym = string;
export type Description = string;
export type Hazardgroup = number;
export type Containmentlevel = number;
export type Safetylevel = string;
export type Molecularmass = number;
export type Proteintype = string;
export type Sequence = string;
export type Personid = number;
export type Bltimestamp = string;
export type Iscreatedbysamplesheet = number;
export type Externalid = string;
export type Componenttypeid = number;
export type Modid = string;
export type Concentrationtypeid = number;

export interface Protein {
  proteinId: Proteinid;
  proposalId: Proposalid;
  name?: Name;
  acronym?: Acronym;
  description?: Description;
  hazardGroup: Hazardgroup;
  containmentLevel: Containmentlevel;
  safetyLevel?: Safetylevel;
  molecularMass?: Molecularmass;
  proteinType?: Proteintype;
  sequence?: Sequence;
  personId?: Personid;
  bltimeStamp: Bltimestamp;
  isCreatedBySampleSheet?: Iscreatedbysamplesheet;
  externalId?: Externalid;
  componentTypeId?: Componenttypeid;
  modId?: Modid;
  concentrationTypeId?: Concentrationtypeid;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withProtein<TBase extends Constructor>(Base: TBase) {
  return class WithProtein extends Base {
    proteinId: Proteinid;
    proposalId: Proposalid;
    name?: Name;
    acronym?: Acronym;
    description?: Description;
    hazardGroup: Hazardgroup;
    containmentLevel: Containmentlevel;
    safetyLevel?: Safetylevel;
    molecularMass?: Molecularmass;
    proteinType?: Proteintype;
    sequence?: Sequence;
    personId?: Personid;
    bltimeStamp: Bltimestamp;
    isCreatedBySampleSheet?: Iscreatedbysamplesheet;
    externalId?: Externalid;
    componentTypeId?: Componenttypeid;
    modId?: Modid;
    concentrationTypeId?: Concentrationtypeid;
  }
}
