/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Datacollectiongroupid = number;
export type Experimenttype = string;

export interface DataCollectionGroup {
  dataCollectionGroupId: Datacollectiongroupid;
  experimentType: Experimenttype;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withDataCollectionGroup<TBase extends Constructor>(Base: TBase) {
  return class WithDataCollectionGroup extends Base {
    dataCollectionGroupId: Datacollectiongroupid;
    experimentType: Experimenttype;
  }
}
