/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Actiontype = string;
export type Status = string;
export type Message = string;

export interface RobotAction {
  actionType: Actiontype;
  status?: Status;
  message?: Message;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withRobotAction<TBase extends Constructor>(Base: TBase) {
  return class WithRobotAction extends Base {
    actionType: Actiontype;
    status?: Status;
    message?: Message;
  }
}
