import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Blsampleimageid = number;
export type Blsampleid = number;
export type Micronsperpixelx = number;
export type Micronsperpixely = number;
export type Offsetx = number;
export type Offsety = number;
/**
 * Url to sample image
 */
export type Url = string;

export interface SampleImage {
  blSampleImageId: Blsampleimageid;
  blSampleId: Blsampleid;
  micronsPerPixelX: Micronsperpixelx;
  micronsPerPixelY: Micronsperpixely;
  offsetX: Offsetx;
  offsetY: Offsety;
  _metadata: SampleImageMetaData;
}
export interface SampleImageMetaData {
  url: Url;
}


export abstract class SampleImageBase extends Entity {
  blSampleImageId: Blsampleimageid;
  blSampleId: Blsampleid;
  micronsPerPixelX: Micronsperpixelx;
  micronsPerPixelY: Micronsperpixely;
  offsetX: Offsetx;
  offsetY: Offsety;
  _metadata: SampleImageMetaData;
}

export abstract class SampleImageSingletonBase extends SingletonEntity {
  blSampleImageId: Blsampleimageid;
  blSampleId: Blsampleid;
  micronsPerPixelX: Micronsperpixelx;
  micronsPerPixelY: Micronsperpixely;
  offsetX: Offsetx;
  offsetY: Offsety;
  _metadata: SampleImageMetaData;
}

export abstract class SampleImageMetaDataBase extends Entity {
  url: Url;
}

export abstract class SampleImageMetaDataSingletonBase extends SingletonEntity {
  url: Url;
}

