/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Code = string;
/**
 * Position in sample change
 */
export type SampleChangerLocation = string;
/**
 * Beamline if container is assigned
 */
export type BeamlineLocation = string;

export interface SampleContainer {
  code: Code;
  sampleChangerLocation?: SampleChangerLocation;
  beamlineLocation?: BeamlineLocation;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSampleContainer<TBase extends Constructor>(Base: TBase) {
  return class WithSampleContainer extends Base {
    code: Code;
    sampleChangerLocation?: SampleChangerLocation;
    beamlineLocation?: BeamlineLocation;
  }
}
