/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An enumeration.
 */
export type SampleOrder = "blSampleId" | "name" | "location" | "datacollections";

type Constructor<T = {}> = new (...args: any[]) => T;
