/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Screeningstrategysubwedgeid = number;
export type Subwedgenumber = number;
export type Rotationaxis = string;
export type Axisstart = number;
export type Axisend = number;
export type Exposuretime = number;
export type Transmission = number;
export type Oscillationrange = number;
export type Completeness = number;
export type Multiplicity = number;
export type Resolution = number;
export type Dosetotal = number;
export type Numberofimages = number;
export type Comments = string;

export interface ScreeningStrategySubWedge {
  screeningStrategySubWedgeId: Screeningstrategysubwedgeid;
  subWedgeNumber?: Subwedgenumber;
  rotationAxis?: Rotationaxis;
  axisStart?: Axisstart;
  axisEnd?: Axisend;
  exposureTime?: Exposuretime;
  transmission?: Transmission;
  oscillationRange?: Oscillationrange;
  completeness?: Completeness;
  multiplicity?: Multiplicity;
  RESOLUTION?: Resolution;
  doseTotal?: Dosetotal;
  numberOfImages?: Numberofimages;
  comments?: Comments;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withScreeningStrategySubWedge<TBase extends Constructor>(Base: TBase) {
  return class WithScreeningStrategySubWedge extends Base {
    screeningStrategySubWedgeId: Screeningstrategysubwedgeid;
    subWedgeNumber?: Subwedgenumber;
    rotationAxis?: Rotationaxis;
    axisStart?: Axisstart;
    axisEnd?: Axisend;
    exposureTime?: Exposuretime;
    transmission?: Transmission;
    oscillationRange?: Oscillationrange;
    completeness?: Completeness;
    multiplicity?: Multiplicity;
    RESOLUTION?: Resolution;
    doseTotal?: Dosetotal;
    numberOfImages?: Numberofimages;
    comments?: Comments;
  }
}
