/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Screeningstrategywedgeid = number;
export type Wedgenumber = number;
export type Resolution = number;
export type Completeness = number;
export type Multiplicity = number;
export type Dosetotal = number;
export type Numberofimages = number;
export type Phi = number;
export type Kappa = number;
export type Chi = number;
export type Comments = string;
export type Wavelength = number;
export type Screeningstrategysubwedgeid = number;
export type Subwedgenumber = number;
export type Rotationaxis = string;
export type Axisstart = number;
export type Axisend = number;
export type Exposuretime = number;
export type Transmission = number;
export type Oscillationrange = number;
export type Completeness1 = number;
export type Multiplicity1 = number;
export type Resolution1 = number;
export type Dosetotal1 = number;
export type Numberofimages1 = number;
export type Comments1 = string;
export type Screeningstrategysubwedge = ScreeningStrategySubWedge[];

export interface ScreeningStrategyWedge {
  screeningStrategyWedgeId: Screeningstrategywedgeid;
  wedgeNumber?: Wedgenumber;
  resolution?: Resolution;
  completeness?: Completeness;
  multiplicity?: Multiplicity;
  doseTotal?: Dosetotal;
  numberOfImages?: Numberofimages;
  phi?: Phi;
  kappa?: Kappa;
  chi?: Chi;
  comments?: Comments;
  wavelength?: Wavelength;
  ScreeningStrategySubWedge?: Screeningstrategysubwedge;
}
export interface ScreeningStrategySubWedge {
  screeningStrategySubWedgeId: Screeningstrategysubwedgeid;
  subWedgeNumber?: Subwedgenumber;
  rotationAxis?: Rotationaxis;
  axisStart?: Axisstart;
  axisEnd?: Axisend;
  exposureTime?: Exposuretime;
  transmission?: Transmission;
  oscillationRange?: Oscillationrange;
  completeness?: Completeness1;
  multiplicity?: Multiplicity1;
  RESOLUTION?: Resolution1;
  doseTotal?: Dosetotal1;
  numberOfImages?: Numberofimages1;
  comments?: Comments1;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withScreeningStrategyWedge<TBase extends Constructor>(Base: TBase) {
  return class WithScreeningStrategyWedge extends Base {
    screeningStrategyWedgeId: Screeningstrategywedgeid;
    wedgeNumber?: Wedgenumber;
    resolution?: Resolution;
    completeness?: Completeness;
    multiplicity?: Multiplicity;
    doseTotal?: Dosetotal;
    numberOfImages?: Numberofimages;
    phi?: Phi;
    kappa?: Kappa;
    chi?: Chi;
    comments?: Comments;
    wavelength?: Wavelength;
    ScreeningStrategySubWedge?: Screeningstrategysubwedge;
  }
}
export function withScreeningStrategySubWedge<TBase extends Constructor>(Base: TBase) {
  return class WithScreeningStrategySubWedge extends Base {
    screeningStrategySubWedgeId: Screeningstrategysubwedgeid;
    subWedgeNumber?: Subwedgenumber;
    rotationAxis?: Rotationaxis;
    axisStart?: Axisstart;
    axisEnd?: Axisend;
    exposureTime?: Exposuretime;
    transmission?: Transmission;
    oscillationRange?: Oscillationrange;
    completeness?: Completeness1;
    multiplicity?: Multiplicity1;
    RESOLUTION?: Resolution1;
    doseTotal?: Dosetotal1;
    numberOfImages?: Numberofimages1;
    comments?: Comments1;
  }
}
