/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Sequenceeventtypeid = number;
export type Name = string;

export interface SequenceEventType {
  sequenceEventTypeId: Sequenceeventtypeid;
  name: Name;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSequenceEventType<TBase extends Constructor>(Base: TBase) {
  return class WithSequenceEventType extends Base {
    sequenceEventTypeId: Sequenceeventtypeid;
    name: Name;
  }
}
