/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Typename = string;

export interface SessionType {
  typeName: Typename;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSessionType<TBase extends Constructor>(Base: TBase) {
  return class WithSessionType extends Base {
    typeName: Typename;
  };
}
