/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Proposalid = number;
export type Shippingname = string;
export type Sendinglabcontactid = number;
export type Returnlabcontactid = number;
/**
 * An enumeration.
 */
export type SafetyLevelEnum = "GREEN" | "YELLOW" | "RED";
export type Comments = string;

export interface ShippingCreateOptional {
  proposalId?: Proposalid;
  shippingName?: Shippingname;
  sendingLabContactId?: Sendinglabcontactid;
  returnLabContactId?: Returnlabcontactid;
  safetyLevel?: SafetyLevelEnum;
  comments?: Comments;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withShippingCreateOptional<TBase extends Constructor>(Base: TBase) {
  return class WithShippingCreateOptional extends Base {
    proposalId?: Proposalid;
    shippingName?: Shippingname;
    sendingLabContactId?: Sendinglabcontactid;
    returnLabContactId?: Returnlabcontactid;
    safetyLevel?: SafetyLevelEnum;
    comments?: Comments;
  }
}
