/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cardname = string;
export type Givenname = string;
export type Familyname = string;

export interface ShippingLabContact {
  cardName: Cardname;
  Person: ShippingLabContactPerson;
}
export interface ShippingLabContactPerson {
  givenName: Givenname;
  familyName: Familyname;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withShippingLabContact<TBase extends Constructor>(Base: TBase) {
  return class WithShippingLabContact extends Base {
    cardName: Cardname;
    Person: ShippingLabContactPerson;
  }
}
export function withShippingLabContactPerson<TBase extends Constructor>(Base: TBase) {
  return class WithShippingLabContactPerson extends Base {
    givenName: Givenname;
    familyName: Familyname;
  }
}
