/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Number of dewars
 */
export type Dewars = number;

export interface ShippingMetaData {
  dewars: Dewars;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withShippingMetaData<TBase extends Constructor>(Base: TBase) {
  return class WithShippingMetaData extends Base {
    dewars: Dewars;
  }
}
