import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Nbhits = number;
export type Nbindexed = number;
export type Laticetype = string;
export type Estimatedresolution = number;
export type Datacollectionid = number;

export interface SSXDataCollectionProcessingStats {
  nbHits: Nbhits;
  nbIndexed: Nbindexed;
  laticeType: Laticetype;
  estimatedResolution: Estimatedresolution;
  dataCollectionId: Datacollectionid;
}


export abstract class SSXDataCollectionProcessingStatsBase extends Entity {
  nbHits: Nbhits;
  nbIndexed: Nbindexed;
  laticeType: Laticetype;
  estimatedResolution: Estimatedresolution;
  dataCollectionId: Datacollectionid;
}

export abstract class SSXDataCollectionProcessingStatsSingletonBase extends SingletonEntity {
  nbHits: Nbhits;
  nbIndexed: Nbindexed;
  laticeType: Laticetype;
  estimatedResolution: Estimatedresolution;
  dataCollectionId: Datacollectionid;
}

