/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Processingcommandline = string;
export type Processingprograms = string;
export type Processingmessage = string;
export type Processingstarttime = string;
export type Processingendtime = string;
export type Processingenvironment = string;
export type Results = string[];

export interface SSXDataCollectionProcessingCreate {
  processingCommandLine?: Processingcommandline;
  processingPrograms?: Processingprograms;
  processingMessage?: Processingmessage;
  processingStartTime?: Processingstarttime;
  processingEndTime?: Processingendtime;
  processingEnvironment?: Processingenvironment;
  results: Results;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSSXDataCollectionProcessingCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXDataCollectionProcessingCreate extends Base {
    processingCommandLine?: Processingcommandline;
    processingPrograms?: Processingprograms;
    processingMessage?: Processingmessage;
    processingStartTime?: Processingstarttime;
    processingEndTime?: Processingendtime;
    processingEnvironment?: Processingenvironment;
    results: Results;
  }
}
