/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Nbhits = number;
export type Nbindexed = number;
export type Laticetype = string;
export type Estimatedresolution = number;
export type UnitCells = number[][];
export type Datacollectionid = number;

export interface SSXDataCollectionProcessing {
  nbHits: Nbhits;
  nbIndexed: Nbindexed;
  laticeType: Laticetype;
  estimatedResolution: Estimatedresolution;
  unit_cells: UnitCells;
  dataCollectionId: Datacollectionid;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSSXDataCollectionProcessing<TBase extends Constructor>(Base: TBase) {
  return class WithSSXDataCollectionProcessing extends Base {
    nbHits: Nbhits;
    nbIndexed: Nbindexed;
    laticeType: Laticetype;
    estimatedResolution: Estimatedresolution;
    unit_cells: UnitCells;
    dataCollectionId: Datacollectionid;
  }
}
