import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UnitCells = number[][];

export interface SSXDataCollectionProcessingCells {
  unit_cells: UnitCells;
}


export abstract class SSXDataCollectionProcessingCellsBase extends Entity {
  unit_cells: UnitCells;
}

export abstract class SSXDataCollectionProcessingCellsSingletonBase extends SingletonEntity {
  unit_cells: UnitCells;
}

