/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UnitCells = number[][];

export interface SSXDataCollectionProcessingCells {
  unit_cells: UnitCells;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSSXDataCollectionProcessingCells<TBase extends Constructor>(Base: TBase) {
  return class WithSSXDataCollectionProcessingCells extends Base {
    unit_cells: UnitCells;
  }
}
