/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Sessionid = number;
export type Starttime = string;
export type Endtime = string;
export type Experimenttype = "SSX-Chip" | "SSX-Jet";
export type Comments = string;
export type Name = string;
export type Support = string;
export type SizeX = number;
export type SizeY = number;
export type SizeZ = number;
export type Abundance = number;
export type Name1 = string;
export type Acronym = string;
export type Name2 = string;
export type Componenttype = "Ligand" | "Buffer" | "JetMaterial";
export type Composition = string;
export type Abundance1 = number;
export type Components = SSXSampleComponentCreate[];
export type Components1 = SSXSampleComponentCreate[];

export interface SSXDataCollectionGroupCreate {
  sessionId: Sessionid;
  startTime: Starttime;
  endTime?: Endtime;
  experimentType?: Experimenttype;
  comments?: Comments;
  sample: SSXSampleCreate;
}
export interface SSXSampleCreate {
  name?: Name;
  support?: Support;
  crystal: SSXCrystalCreate;
  components: Components1;
}
export interface SSXCrystalCreate {
  size_X?: SizeX;
  size_Y?: SizeY;
  size_Z?: SizeZ;
  abundance?: Abundance;
  protein: SSXProteinCreate;
  components: Components;
}
export interface SSXProteinCreate {
  name?: Name1;
  acronym?: Acronym;
}
export interface SSXSampleComponentCreate {
  name?: Name2;
  componentType: Componenttype;
  composition?: Composition;
  abundance?: Abundance1;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSSXDataCollectionGroupCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXDataCollectionGroupCreate extends Base {
    sessionId: Sessionid;
    startTime: Starttime;
    endTime?: Endtime;
    experimentType?: Experimenttype;
    comments?: Comments;
    sample: SSXSampleCreate;
  }
}
export function withSSXSampleCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXSampleCreate extends Base {
    name?: Name;
    support?: Support;
    crystal: SSXCrystalCreate;
    components: Components1;
  }
}
export function withSSXCrystalCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXCrystalCreate extends Base {
    size_X?: SizeX;
    size_Y?: SizeY;
    size_Z?: SizeZ;
    abundance?: Abundance;
    protein: SSXProteinCreate;
    components: Components;
  }
}
export function withSSXProteinCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXProteinCreate extends Base {
    name?: Name1;
    acronym?: Acronym;
  }
}
export function withSSXSampleComponentCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXSampleComponentCreate extends Base {
    name?: Name2;
    componentType: Componenttype;
    composition?: Composition;
    abundance?: Abundance1;
  }
}
