/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Acronym = string;

export interface SSXProteinCreate {
  name?: Name;
  acronym?: Acronym;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSSXProteinCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXProteinCreate extends Base {
    name?: Name;
    acronym?: Acronym;
  }
}
