/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Blsampleid = number;
export type Diffractionplanid = number;
export type Crystalid = number;
export type Containerid = number;
export type Name = string;
export type Code = string;
export type Location = string;
export type Holderlength = number;
export type Looplength = number;
export type Looptype = string;
export type Wirewidth = number;
export type Comments = string;
export type Completionstage = string;
export type Structurestage = string;
export type Publicationstage = string;
export type Publicationcomments = string;
export type Blsamplestatus = string;
export type Isinsamplechanger = number;
export type Lastknowncenteringposition = string;
export type Recordtimestamp = string;
export type Smiles = string;
export type Lastimageurl = string;
export type Positionid = number;
export type Blsubsampleid = number;
export type Screencomponentgroupid = number;
export type Volume = number;
export type Dimension1 = number;
export type Dimension2 = number;
export type Dimension3 = number;
export type Shape = string;
export type Sublocation = number;
export type Crystalid1 = number;
export type Diffractionplanid1 = number;
export type Proteinid = number;
export type Crystaluuid = string;
export type Name1 = string;
export type Spacegroup = string;
export type Morphology = string;
export type Color = string;
export type SizeX = number;
export type SizeY = number;
export type SizeZ = number;
export type CellA = number;
export type CellB = number;
export type CellC = number;
export type CellAlpha = number;
export type CellBeta = number;
export type CellGamma = number;
export type Comments1 = string;
export type Pdbfilename = string;
export type Pdbfilepath = string;
export type Recordtimestamp1 = string;
export type Abundance = number;
export type Packingfraction = number;
export type Proteinid1 = number;
export type Proposalid = number;
export type Name2 = string;
export type Acronym = string;
export type Description = string;
export type Hazardgroup = number;
export type Containmentlevel = number;
export type Safetylevel = string;
export type Molecularmass = number;
export type Proteintype = string;
export type Sequence = string;
export type Personid = number;
export type Bltimestamp = string;
export type Iscreatedbysamplesheet = number;
export type Externalid = string;
export type Componenttypeid = number;
export type Modid = string;
export type Concentrationtypeid = number;
export type Crystalcompositionid = number;
export type Componentid = number;
export type Crystalid2 = number;
export type Concentrationtypeid1 = number;
export type Abundance1 = number;
export type Ratio = number;
export type Ph = number;
export type Componentid1 = number;
export type Componenttypeid1 = number;
export type Proposalid1 = number;
export type Name3 = string;
export type Composition = string;
export type Concentration = number;
export type Componenttypeid2 = number;
export type Name4 = string;
export type CrystalCompositions = CrystalCompositionResponse[];
export type Samplecompositionid = number;
export type Componentid2 = number;
export type Blsampleid1 = number;
export type Concentrationtypeid2 = number;
export type Abundance2 = number;
export type Ratio1 = number;
export type Ph1 = number;
export type SampleCompositions = SampleCompositionResponse[];

export interface SSXSampleResponse {
  blSampleId: Blsampleid;
  diffractionPlanId?: Diffractionplanid;
  crystalId?: Crystalid;
  containerId?: Containerid;
  name?: Name;
  code?: Code;
  location?: Location;
  holderLength?: Holderlength;
  loopLength?: Looplength;
  loopType?: Looptype;
  wireWidth?: Wirewidth;
  comments?: Comments;
  completionStage?: Completionstage;
  structureStage?: Structurestage;
  publicationStage?: Publicationstage;
  publicationComments?: Publicationcomments;
  blSampleStatus?: Blsamplestatus;
  isInSampleChanger?: Isinsamplechanger;
  lastKnownCenteringPosition?: Lastknowncenteringposition;
  recordTimeStamp: Recordtimestamp;
  SMILES?: Smiles;
  lastImageURL?: Lastimageurl;
  positionId?: Positionid;
  blSubSampleId?: Blsubsampleid;
  screenComponentGroupId?: Screencomponentgroupid;
  volume?: Volume;
  dimension1?: Dimension1;
  dimension2?: Dimension2;
  dimension3?: Dimension3;
  shape?: Shape;
  subLocation?: Sublocation;
  Crystal: CrystalResponse;
  sample_compositions: SampleCompositions;
}
export interface CrystalResponse {
  crystalId: Crystalid1;
  diffractionPlanId?: Diffractionplanid1;
  proteinId: Proteinid;
  crystalUUID?: Crystaluuid;
  name?: Name1;
  spaceGroup?: Spacegroup;
  morphology?: Morphology;
  color?: Color;
  size_X?: SizeX;
  size_Y?: SizeY;
  size_Z?: SizeZ;
  cell_a?: CellA;
  cell_b?: CellB;
  cell_c?: CellC;
  cell_alpha?: CellAlpha;
  cell_beta?: CellBeta;
  cell_gamma?: CellGamma;
  comments?: Comments1;
  pdbFileName?: Pdbfilename;
  pdbFilePath?: Pdbfilepath;
  recordTimeStamp: Recordtimestamp1;
  abundance?: Abundance;
  packingFraction?: Packingfraction;
  Protein: Protein;
  crystal_compositions: CrystalCompositions;
}
export interface Protein {
  proteinId: Proteinid1;
  proposalId: Proposalid;
  name?: Name2;
  acronym?: Acronym;
  description?: Description;
  hazardGroup: Hazardgroup;
  containmentLevel: Containmentlevel;
  safetyLevel?: Safetylevel;
  molecularMass?: Molecularmass;
  proteinType?: Proteintype;
  sequence?: Sequence;
  personId?: Personid;
  bltimeStamp: Bltimestamp;
  isCreatedBySampleSheet?: Iscreatedbysamplesheet;
  externalId?: Externalid;
  componentTypeId?: Componenttypeid;
  modId?: Modid;
  concentrationTypeId?: Concentrationtypeid;
}
export interface CrystalCompositionResponse {
  crystalCompositionId: Crystalcompositionid;
  componentId: Componentid;
  crystalId: Crystalid2;
  concentrationTypeId?: Concentrationtypeid1;
  abundance?: Abundance1;
  ratio?: Ratio;
  ph?: Ph;
  Component: ComponentResponse;
}
export interface ComponentResponse {
  componentId: Componentid1;
  componentTypeId: Componenttypeid1;
  proposalId?: Proposalid1;
  name: Name3;
  composition?: Composition;
  concentration?: Concentration;
  ComponentType: ComponentType;
}
export interface ComponentType {
  componentTypeId: Componenttypeid2;
  name: Name4;
}
export interface SampleCompositionResponse {
  sampleCompositionId: Samplecompositionid;
  componentId: Componentid2;
  blSampleId: Blsampleid1;
  concentrationTypeId?: Concentrationtypeid2;
  abundance?: Abundance2;
  ratio?: Ratio1;
  ph?: Ph1;
  Component: ComponentResponse;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSSXSampleResponse<TBase extends Constructor>(Base: TBase) {
  return class WithSSXSampleResponse extends Base {
    blSampleId: Blsampleid;
    diffractionPlanId?: Diffractionplanid;
    crystalId?: Crystalid;
    containerId?: Containerid;
    name?: Name;
    code?: Code;
    location?: Location;
    holderLength?: Holderlength;
    loopLength?: Looplength;
    loopType?: Looptype;
    wireWidth?: Wirewidth;
    comments?: Comments;
    completionStage?: Completionstage;
    structureStage?: Structurestage;
    publicationStage?: Publicationstage;
    publicationComments?: Publicationcomments;
    blSampleStatus?: Blsamplestatus;
    isInSampleChanger?: Isinsamplechanger;
    lastKnownCenteringPosition?: Lastknowncenteringposition;
    recordTimeStamp: Recordtimestamp;
    SMILES?: Smiles;
    lastImageURL?: Lastimageurl;
    positionId?: Positionid;
    blSubSampleId?: Blsubsampleid;
    screenComponentGroupId?: Screencomponentgroupid;
    volume?: Volume;
    dimension1?: Dimension1;
    dimension2?: Dimension2;
    dimension3?: Dimension3;
    shape?: Shape;
    subLocation?: Sublocation;
    Crystal: CrystalResponse;
    sample_compositions: SampleCompositions;
  }
}
export function withCrystalResponse<TBase extends Constructor>(Base: TBase) {
  return class WithCrystalResponse extends Base {
    crystalId: Crystalid1;
    diffractionPlanId?: Diffractionplanid1;
    proteinId: Proteinid;
    crystalUUID?: Crystaluuid;
    name?: Name1;
    spaceGroup?: Spacegroup;
    morphology?: Morphology;
    color?: Color;
    size_X?: SizeX;
    size_Y?: SizeY;
    size_Z?: SizeZ;
    cell_a?: CellA;
    cell_b?: CellB;
    cell_c?: CellC;
    cell_alpha?: CellAlpha;
    cell_beta?: CellBeta;
    cell_gamma?: CellGamma;
    comments?: Comments1;
    pdbFileName?: Pdbfilename;
    pdbFilePath?: Pdbfilepath;
    recordTimeStamp: Recordtimestamp1;
    abundance?: Abundance;
    packingFraction?: Packingfraction;
    Protein: Protein;
    crystal_compositions: CrystalCompositions;
  }
}
export function withProtein<TBase extends Constructor>(Base: TBase) {
  return class WithProtein extends Base {
    proteinId: Proteinid1;
    proposalId: Proposalid;
    name?: Name2;
    acronym?: Acronym;
    description?: Description;
    hazardGroup: Hazardgroup;
    containmentLevel: Containmentlevel;
    safetyLevel?: Safetylevel;
    molecularMass?: Molecularmass;
    proteinType?: Proteintype;
    sequence?: Sequence;
    personId?: Personid;
    bltimeStamp: Bltimestamp;
    isCreatedBySampleSheet?: Iscreatedbysamplesheet;
    externalId?: Externalid;
    componentTypeId?: Componenttypeid;
    modId?: Modid;
    concentrationTypeId?: Concentrationtypeid;
  }
}
export function withCrystalCompositionResponse<TBase extends Constructor>(Base: TBase) {
  return class WithCrystalCompositionResponse extends Base {
    crystalCompositionId: Crystalcompositionid;
    componentId: Componentid;
    crystalId: Crystalid2;
    concentrationTypeId?: Concentrationtypeid1;
    abundance?: Abundance1;
    ratio?: Ratio;
    ph?: Ph;
    Component: ComponentResponse;
  }
}
export function withComponentResponse<TBase extends Constructor>(Base: TBase) {
  return class WithComponentResponse extends Base {
    componentId: Componentid1;
    componentTypeId: Componenttypeid1;
    proposalId?: Proposalid1;
    name: Name3;
    composition?: Composition;
    concentration?: Concentration;
    ComponentType: ComponentType;
  }
}
export function withComponentType<TBase extends Constructor>(Base: TBase) {
  return class WithComponentType extends Base {
    componentTypeId: Componenttypeid2;
    name: Name4;
  }
}
export function withSampleCompositionResponse<TBase extends Constructor>(Base: TBase) {
  return class WithSampleCompositionResponse extends Base {
    sampleCompositionId: Samplecompositionid;
    componentId: Componentid2;
    blSampleId: Blsampleid1;
    concentrationTypeId?: Concentrationtypeid2;
    abundance?: Abundance2;
    ratio?: Ratio1;
    ph?: Ph1;
    Component: ComponentResponse;
  }
}
