/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Componenttype = "Ligand" | "Buffer" | "JetMaterial";
export type Composition = string;
export type Abundance = number;

export interface SSXSampleComponentCreate {
  name?: Name;
  componentType: Componenttype;
  composition?: Composition;
  abundance?: Abundance;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSSXSampleComponentCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXSampleComponentCreate extends Base {
    name?: Name;
    componentType: Componenttype;
    composition?: Composition;
    abundance?: Abundance;
  }
}
