/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Type = "XrayDetection" | "XrayExposure" | "LaserExcitation" | "ReactionTrigger";
export type Name1 = string;
export type Time = string;
export type Duration = number;
export type Period = number;
export type Repetition = number;
export type Events = SSXSequenceEventCreate[];

export interface SSXSequenceCreate {
  name?: Name;
  events: Events;
}
export interface SSXSequenceEventCreate {
  type: Type;
  name?: Name1;
  time: Time;
  duration?: Duration;
  period?: Period;
  repetition?: Repetition;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withSSXSequenceCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXSequenceCreate extends Base {
    name?: Name;
    events: Events;
  }
}
export function withSSXSequenceEventCreate<TBase extends Constructor>(Base: TBase) {
  return class WithSSXSequenceEventCreate extends Base {
    type: Type;
    name?: Name1;
    time: Time;
    duration?: Duration;
    period?: Period;
    repetition?: Repetition;
  }
}
