/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Run = string;
export type Runid = number;
export type Startdate = string;
export type Enddate = string;

export interface VRun {
  run: Run;
  runId: Runid;
  startDate: Startdate;
  endDate: Enddate;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withVRun<TBase extends Constructor>(Base: TBase) {
  return class WithVRun extends Base {
    run: Run;
    runId: Runid;
    startDate: Startdate;
    endDate: Enddate;
  }
}
