/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Workflowid = number;
export type Workflowstepid = number;
export type Workflowsteptype = string;
export type Status = string;
export type Comments = string;

export interface WorkflowStep {
  workflowId: Workflowid;
  workflowStepId: Workflowstepid;
  workflowStepType?: Workflowsteptype;
  status?: Status;
  comments?: Comments;
  _metadata: WorkflowStepMetaData;
}
export interface WorkflowStepMetaData {
  attachments: Attachments;
}
/**
 * Attachment statuses
 */
export interface Attachments {
  [k: string]: boolean;
}

type Constructor<T = {}> = new (...args: any[]) => T;
export function withWorkflowStep<TBase extends Constructor>(Base: TBase) {
  return class WithWorkflowStep extends Base {
    workflowId: Workflowid;
    workflowStepId: Workflowstepid;
    workflowStepType?: Workflowsteptype;
    status?: Status;
    comments?: Comments;
    _metadata: WorkflowStepMetaData;
  }
}
export function withWorkflowStepMetaData<TBase extends Constructor>(Base: TBase) {
  return class WithWorkflowStepMetaData extends Base {
    attachments: Attachments;
  }
  /**
   * Attachment statuses
   */
}
export function withAttachments<TBase extends Constructor>(Base: TBase) {
  return class WithAttachments extends Base {
    [k: string]: boolean;
  }
}
