import { Entity } from '@rest-hooks/rest';
import { SingletonEntity } from 'api/resources/Base/Singleton';

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Workflowid = number;
export type Workflowstepid = number;
export type Workflowsteptype = string;
export type Status = string;
export type Comments = string;

export interface WorkflowStep {
  workflowId: Workflowid;
  workflowStepId: Workflowstepid;
  workflowStepType?: Workflowsteptype;
  status?: Status;
  comments?: Comments;
  _metadata: WorkflowStepMetaData;
}
export interface WorkflowStepMetaData {
  attachments: Attachments;
}
/**
 * Attachment statuses
 */
export interface Attachments {
  [k: string]: boolean;
}


export abstract class WorkflowStepBase extends Entity {
  workflowId: Workflowid;
  workflowStepId: Workflowstepid;
  workflowStepType?: Workflowsteptype;
  status?: Status;
  comments?: Comments;
  _metadata: WorkflowStepMetaData;
}

export abstract class WorkflowStepSingletonBase extends SingletonEntity {
  workflowId: Workflowid;
  workflowStepId: Workflowstepid;
  workflowStepType?: Workflowsteptype;
  status?: Status;
  comments?: Comments;
  _metadata: WorkflowStepMetaData;
}

export abstract class WorkflowStepMetaDataBase extends Entity {
  attachments: Attachments;
}
/**
 * Attachment statuses
 */

export abstract class WorkflowStepMetaDataSingletonBase extends SingletonEntity {
  attachments: Attachments;
}
/**
 * Attachment statuses
 */

