site_name: py-ispyb-ui
site_url: https://ispyb.github.io/py-ispyb-ui/
repo_name: 'ispyb/py-ispyb-ui'
repo_url: 'https://github.com/ispyb/py-ispyb-ui'
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - Installation: installation.md

plugins:
  - search

markdown_extensions:
  - codehilite
  - attr_list
  - admonition
